// National coverage data: 50 states + DC, counties per state, sample cities per county.
// Counties are real administrative divisions; cities are representative samples per county.

export const US_STATES = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "DC", name: "District of Columbia" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

// Representative counties + sample cities per state. Real county names; cities are
// a representative sample (not exhaustive) to keep the dataset manageable.
export const STATE_COUNTIES = {
  AL: {
    Jefferson: ["Birmingham", "Hoover", "Vestavia Hills"],
    Madison: ["Huntsville", "Madison"],
    Mobile: ["Mobile", "Prichard"],
    Montgomery: ["Montgomery", "Pike Road"],
    Shelby: ["Alabaster", "Pelham", "Columbiana"],
    Baldwin: ["Daphne", "Fairhope", "Gulf Shores"],
  },
  AK: {
    Anchorage: ["Anchorage"],
    Fairbanks_North_Star: ["Fairbanks", "North Pole"],
    Matanuska_Susitna: ["Wasilla", "Palmer"],
    Juneau: ["Juneau"],
  },
  AZ: {
    Maricopa: ["Phoenix", "Mesa", "Scottsdale", "Tempe", "Glendale", "Chandler"],
    Pima: ["Tucson", "South Tucson"],
    Pinal: ["Casa Grande", "Maricopa", "Florence"],
    Yavapai: ["Prescott", "Sedona", "Cottonwood"],
    Coconino: ["Flagstaff", "Sedona"],
    Yuma: ["Yuma", "Somerton"],
  },
  AR: {
    Pulaski: ["Little Rock", "North Little Rock", "Sherwood"],
    Benton: ["Bentonville", "Rogers", "Bella Vista"],
    Washington: ["Fayetteville", "Springdale"],
    Sebastian: ["Fort Smith", "Greenwood"],
    Garland: ["Hot Springs"],
  },
  CA: {
    Los_Angeles: ["Los Angeles", "Long Beach", "Glendale", "Santa Clarita", "Pasadena", "Torrance"],
    San_Diego: ["San Diego", "Chula Vista", "Oceanside", "Escondido"],
    Orange: ["Anaheim", "Santa Ana", "Irvine", "Huntington Beach", "Costa Mesa"],
    Riverside: ["Riverside", "Moreno Valley", "Palm Springs", "Corona"],
    San_Bernardino: ["San Bernardino", "Ontario", "Rancho Cucamonga", "Victorville"],
    Santa_Clara: ["San Jose", "Sunnyvale", "Santa Clara", "Palo Alto", "Mountain View"],
    Alameda: ["Oakland", "Fremont", "Berkeley", "Hayward"],
    Sacramento: ["Sacramento", "Elk Grove", "Folsom", "Citrus Heights"],
    San_Francisco: ["San Francisco"],
    Contra_Costa: ["Concord", "Richmond", "Walnut Creek", "Antioch"],
    Fresno: ["Fresno", "Clovis"],
    Ventura: ["Ventura", "Oxnard", "Thousand Oaks", "Simi Valley"],
  },
  CO: {
    Denver: ["Denver"],
    El_Paso: ["Colorado Springs", "Fountain"],
    Arapahoe: ["Centennial", "Aurora", "Littleton", "Englewood"],
    Jefferson: ["Lakewood", "Arvada", "Wheat Ridge", "Golden"],
    Adams: ["Thornton", "Westminster", "Commerce City", "Northglenn"],
    Boulder: ["Boulder", "Longmont", "Lafayette"],
    Larimer: ["Fort Collins", "Loveland"],
    Douglas: ["Castle Rock", "Parker", "Highlands Ranch"],
  },
  CT: {
    Fairfield: ["Bridgeport", "Stamford", "Norwalk", "Danbury", "Greenwich"],
    Hartford: ["Hartford", "New Britain", "West Hartford", "Bristol"],
    New_Haven: ["New Haven", "Waterbury", "Meriden", "Hamden"],
    New_London: ["New London", "Norwich", "Groton"],
  },
  DE: {
    New_Castle: ["Wilmington", "Newark", "Dover"],
    Sussex: ["Georgetown", "Seaford", "Lewes"],
    Kent: ["Dover", "Smyrna", "Milford"],
  },
  DC: {
    District_of_Columbia: ["Washington"],
  },
  FL: {
    Miami_Dade: ["Miami", "Hialeah", "Coral Gables", "Doral", "Homestead"],
    Broward: ["Fort Lauderdale", "Hollywood", "Pompano Beach", "Coral Springs", "Davie"],
    Palm_Beach: ["West Palm Beach", "Boca Raton", "Boynton Beach", "Delray Beach", "Wellington"],
    Hillsborough: ["Tampa", "Temple Terrace", "Plant City"],
    Orange: ["Orlando", "Winter Park", "Ocoee", "Apopka"],
    Pinellas: ["St. Petersburg", "Clearwater", "Largo", "Pinellas Park"],
    Duval: ["Jacksonville"],
    Lee: ["Fort Myers", "Cape Coral", "Bonita Springs"],
    Polk: ["Lakeland", "Winter Haven", "Bartow"],
    Brevard: ["Melbourne", "Palm Bay", "Titusville", "Cocoa"],
  },
  GA: {
    Fulton: ["Atlanta", "Sandy Springs", "Roswell", "Alpharetta", "Johns Creek"],
    Gwinnett: ["Lawrenceville", "Sandy Springs", "Duluth", "Snellville", "Suwanee"],
    Cobb: ["Marietta", "Smyrna", "Kennesaw", "Acworth"],
    DeKalb: ["Decatur", "Stone Mountain", "Dunwoody", "Brookhaven"],
    Chatham: ["Savannah", "Pooler", "Garden City"],
    Richmond: ["Augusta", "Hephzibah"],
    Muscogee: ["Columbus", "Fort Moore"],
  },
  HI: {
    Honolulu: ["Honolulu", "Pearl City", "Kapolei", "Kailua"],
    Hawaii: ["Hilo", "Kailua-Kona"],
    Maui: ["Kahului", "Wailuku", "Lahaina"],
  },
  ID: {
    Ada: ["Boise", "Meridian", "Garden City", "Eagle"],
    Canyon: ["Nampa", "Caldwell", "Middleton"],
    Kootenai: ["Coeur d'Alene", "Post Falls", "Hayden"],
    Bonneville: ["Idaho Falls", "Ammon", "Iona"],
  },
  IL: {
    Cook: ["Chicago", "Evanston", "Oak Park", "Skokie", "Schaumburg", "Des Plaines"],
    DuPage: ["Wheaton", "Naperville", "Elmhurst", "Downers Grove", "Glen Ellyn"],
    Lake: ["Waukegan", "Lake Forest", "Highland Park", "Gurnee"],
    Will: ["Joliet", "Romeoville", "Plainfield", "Bolingbrook"],
    Kane: ["Aurora", "Elgin", "Geneva", "St. Charles"],
    McHenry: ["Woodstock", "Crystal Lake", "McHenry", "Algonquin"],
    Madison: ["Edwardsville", "Alton", "Granite City", "Collinsville"],
    Sangamon: ["Springfield", "Rochester", "Sherman"],
  },
  IN: {
    Marion: ["Indianapolis", "Lawrence", "Beech Grove", "Speedway"],
    Lake: ["Gary", "Hammond", "Merrillville", "Crown Point"],
    Allen: ["Fort Wayne", "New Haven", "Huntertown"],
    Hamilton: ["Carmel", "Fishers", "Noblesville", "Westfield"],
    St_Joseph: ["South Bend", "Mishawaka", "Granger"],
    Hendricks: ["Plainfield", "Avon", "Brownsburg", "Danville"],
  },
  IA: {
    Polk: ["Des Moines", "Ankeny", "Altoona", "West Des Moines"],
    Linn: ["Cedar Rapids", "Marion", "Hiawatha"],
    Scott: ["Davenport", "Bettendorf", "Eldridge"],
    Black_Hawk: ["Waterloo", "Cedar Falls"],
    Johnson: ["Iowa City", "Coralville", "North Liberty"],
  },
  KS: {
    Johnson: ["Overland Park", "Olathe", "Lenexa", "Shawnee", "Leawood"],
    Sedgwick: ["Wichita", "Derby", "Haysville", "Park City"],
    Shawnee: ["Topeka", "Auburn", "Silver Lake"],
    Wyandotte: ["Kansas City", "Bonner Springs"],
    Douglas: ["Lawrence", "Eudora", "Baldwin City"],
  },
  KY: {
    Jefferson: ["Louisville", "Shively", "St. Matthews", "Lyndon"],
    Fayette: ["Lexington", "Athens"],
    Kenton: ["Covington", "Erlanger", "Independence"],
    Boone: ["Florence", "Burlington", "Union"],
    Warren: ["Bowling Green", "Oakland", "Smiths Grove"],
  },
  LA: {
    Orleans: ["New Orleans"],
    East_Baton_Rouge: ["Baton Rouge", "Baker", "Zachary"],
    Jefferson: ["Metairie", "Kenner", "Harahan", "Gretna"],
    Caddo: ["Shreveport", "Blanchard", "Greenwood"],
    Lafayette: ["Lafayette", "Youngsville", "Carencro", "Broussard"],
    St_Tammany: ["Slidell", "Mandeville", "Covington", "Madisonville"],
  },
  ME: {
    Cumberland: ["Portland", "South Portland", "Westbrook", "Falmouth"],
    Penobscot: ["Bangor", "Brewer", "Old Town", "Orono"],
    York: ["Biddeford", "Saco", "Sanford", "Kittery"],
    Kennebec: ["Augusta", "Waterville", "Gardiner"],
  },
  MD: {
    Montgomery: ["Rockville", "Silver Spring", "Bethesda", "Gaithersburg", "Germantown"],
    Prince_Georges: ["Upper Marlboro", "Bowie", "College Park", "Laurel", "Greenbelt"],
    Baltimore: ["Baltimore", "Towson", "Cockeysville", "Catonsville"],
    Howard: ["Columbia", "Ellicott City", "Laurel", "Clarksville"],
    Anne_Arundel: ["Annapolis", "Glen Burnie", "Severna Park", "Arnold"],
    Frederick: ["Frederick", "Brunswick", "Walkersville", "Middletown"],
  },
  MA: {
    Suffolk: ["Boston", "Revere", "Chelsea", "Winthrop"],
    Middlesex: ["Cambridge", "Lowell", "Newton", "Somerville", "Framingham", "Waltham"],
    Norfolk: ["Quincy", "Brookline", "Weymouth", "Franklin", "Norwood"],
    Essex: ["Lynn", "Salem", "Lawrence", "Haverhill", "Gloucester"],
    Worcester: ["Worcester", "Fitchburg", "Leominster", "Shrewsbury", "Gardner"],
    Plymouth: ["Plymouth", "Brockton", "Bridgewater", "Kingston"],
  },
  MI: {
    Wayne: ["Detroit", "Dearborn", "Livonia", "Taylor", "Westland", "Garden City"],
    Oakland: ["Troy", "Southfield", "Royal Oak", "Pontiac", "Farmington Hills", "Rochester Hills"],
    Macomb: ["Warren", "Sterling Heights", "Clinton Township", "St. Clair Shores", "Roseville"],
    Kent: ["Grand Rapids", "Grandville", "Walker", "Cedar Springs"],
    Ingham: ["Lansing", "East Lansing", "Mason", "Okemos"],
    Washtenaw: ["Ann Arbor", "Ypsilanti", "Chelsea", "Dexter"],
    Genesee: ["Flint", "Flushing", "Grand Blanc", "Davison"],
  },
  MN: {
    Hennepin: ["Minneapolis", "Bloomington", "Edina", "Plymouth", "Brooklyn Park", "Maple Grove"],
    Ramsey: ["St. Paul", "Roseville", "Maplewood", "White Bear Lake"],
    Dakota: ["Hastings", "Eagan", "Burnsville", "Apple Valley", "Lakeville"],
    Anoka: ["Anoka", "Coon Rapids", "Blaine", "Fridley", "Andover"],
    St_Louis: ["Duluth", "Hermantown", "Proctor", "Virginia"],
    Olmsted: ["Rochester", "Byron", "Stewartville"],
  },
  MS: {
    Hinds: ["Jackson", "Byram", "Clinton", "Raymond"],
    Harrison: ["Gulfport", "Biloxi", "D'Iberville", "Long Beach"],
    Rankin: ["Brandon", "Pearl", "Flowood", "Richland"],
    DeSoto: ["Southaven", "Olive Branch", "Hernando", "Horn Lake"],
  },
  MO: {
    St_Louis: ["St. Louis", "Clayton", "Florissant", "Chesterfield", "Kirkwood", "University City"],
    Jackson: ["Kansas City", "Independence", "Lee's Summit", "Blue Springs", "Grandview"],
    St_Louis_City: ["St. Louis"],
    St_Charles: ["St. Charles", "St. Peters", "O'Fallon", "Wentzville", "Lake Saint Louis"],
    Greene: ["Springfield", "Republic", "Nixa", "Ozark"],
    Boone: ["Columbia", "Ashland", "Rocheport"],
  },
  MT: {
    Yellowstone: ["Billings", "Laurel", "Shepherd"],
    Missoula: ["Missoula", "Lolo", "Seeley Lake"],
    Gallatin: ["Bozeman", "Belgrade", "Manhattan"],
    Cascade: ["Great Falls", "Belt", "Cascade"],
    Flathead: ["Kalispell", "Whitefish", "Columbia Falls"],
  },
  NE: {
    Douglas: ["Omaha", "Bennington", "Waterloo"],
    Lancaster: ["Lincoln", "Waverly", "Hickman"],
    Sarpy: ["Papillion", "La Vista", "Bellevue", "Gretna", "Springfield"],
    Hall: ["Grand Island", "Wood River", "Doniphan"],
  },
  NV: {
    Clark: ["Las Vegas", "Henderson", "North Las Vegas", "Boulder City", "Mesquite"],
    Washoe: ["Reno", "Sparks", "Sun Valley", "Verdi"],
    Carson_City: ["Carson City"],
  },
  NH: {
    Hillsborough: ["Manchester", "Nashua", "Merrimack", "Bedford", "Goffstown"],
    Rockingham: ["Portsmouth", "Derry", "Salem", "Exeter", "Londonderry"],
    Merrimack: ["Concord", "Franklin", "Pembroke", "Hooksett"],
    Strafford: ["Dover", "Rochester", "Durham", "Somersworth"],
  },
  NJ: {
    Bergen: ["Hackensack", "Teaneck", "Fort Lee", "Englewood", "Paramus"],
    Essex: ["Newark", "East Orange", "Montclair", "Bloomfield", "Irvington"],
    Hudson: ["Jersey City", "Hoboken", "Bayonne", "Union City", "Secaucus"],
    Middlesex: ["New Brunswick", "Edison", "Woodbridge", "Perth Amboy", "Piscataway"],
    Monmouth: ["Freehold", "Asbury Park", "Long Branch", "Middletown", "Red Bank"],
    Morris: ["Morristown", "Parsippany", "Dover", "Madison", "Rockaway"],
    Ocean: ["Toms River", "Lakewood", "Brick", "Jackson", "Manchester"],
    Camden: ["Camden", "Cherry Hill", "Gloucester", "Pennsauken"],
  },
  NM: {
    Bernalillo: ["Albuquerque", "Rio Rancho", "Los Ranchos", "Tijeras"],
    Santa_Fe: ["Santa Fe", "Edgewood"],
    Dona_Ana: ["Las Cruces", "Sunland Park", "Mesilla"],
    Sandoval: ["Rio Rancho", "Bernalillo", "Cuba"],
  },
  NY: {
    New_York: ["New York City (Manhattan)"],
    Kings: ["Brooklyn"],
    Queens: ["Queens"],
    Bronx: ["The Bronx"],
    Richmond: ["Staten Island"],
    Nassau: ["Hempstead", "Freeport", "Long Beach", "Garden City", "Oyster Bay"],
    Suffolk: ["Brookhaven", "Babylon", "Islip", "Smithtown", "Riverhead"],
    Westchester: ["Yonkers", "New Rochelle", "White Plains", "Mount Vernon", "Scarsdale"],
    Erie: ["Buffalo", "Cheektowaga", "Tonawanda", "Amherst", "Lancaster"],
    Monroe: ["Rochester", "Greece", "Irondequoit", "Brighton", "Chili"],
    Onondaga: ["Syracuse", "DeWitt", "Camillus", "Liverpool"],
    Albany: ["Albany", "Cohoes", "Watervliet", "Bethlehem"],
  },
  NC: {
    Mecklenburg: ["Charlotte", "Cornelius", "Huntersville", "Matthews", "Mint Hill"],
    Wake: ["Raleigh", "Cary", "Apex", "Holly Springs", "Morrisville", "Garner"],
    Guilford: ["Greensboro", "High Point", "Jamestown", "Summerfield"],
    Forsyth: ["Winston-Salem", "Kernersville", "Clemmons", "Lewisville"],
    Durham: ["Durham", "Raleigh"],
    Cumberland: ["Fayetteville", "Hope Mills", "Spring Lake"],
    Buncombe: ["Asheville", "Black Mountain", "Weaverville"],
    New_Hanover: ["Wilmington", "Carolina Beach", "Wrightsville Beach"],
  },
  ND: {
    Cass: ["Fargo", "West Fargo", "Horace", "Kindred"],
    Burleigh: ["Bismarck", "Lincoln", "Mandan"],
    Grand_Forks: ["Grand Forks", "Thompson", "Emerado"],
  },
  OH: {
    Cuyahoga: ["Cleveland", "Lakewood", "Euclid", "Parma", "Beachwood", "Strongsville"],
    Franklin: ["Columbus", "Dublin", "Westerville", "Gahanna", "Hilliard", "Reynoldsburg"],
    Hamilton: ["Cincinnati", "Columbus", "Forest Park", "Norwood", "Springdale"],
    Summit: ["Akron", "Barberton", "Cuyahoga Falls", "Fairlawn", "Stow"],
    Montgomery: ["Dayton", "Kettering", "Huber Heights", "Trotwood", "Centerville"],
    Lucas: ["Toledo", "Sylvania", "Maumee", "Oregon"],
    Stark: ["Canton", "Massillon", "North Canton", "Louisville"],
    Butler: ["Hamilton", "Middletown", "Fairfield", "Oxford"],
  },
  OK: {
    Oklahoma: ["Oklahoma City", "Edmond", "Norman", "Yukon", "Mustang", "Del City"],
    Tulsa: ["Tulsa", "Broken Arrow", "Sand Springs", "Jenks", "Owasso"],
    Cleveland: ["Norman", "Moore", "Noble"],
    Canadian: ["Yukon", "Mustang", "El Reno", "Piedmont"],
  },
  OR: {
    Multnomah: ["Portland", "Gresham", "Troutdale", "Fairview", "Wood Village"],
    Washington: ["Hillsboro", "Beaverton", "Tigard", "Tualatin", "Cedar Mill"],
    Clackamas: ["Oregon City", "Lake Oswego", "Milwaukie", "West Linn", "Happy Valley"],
    Lane: ["Eugene", "Springfield", "Creswell", "Veneta"],
    Marion: ["Salem", "Silverton", "Stayton", "Woodburn"],
    Deschutes: ["Bend", "Redmond", "Sisters", "La Pine"],
  },
  PA: {
    Philadelphia: ["Philadelphia"],
    Allegheny: ["Pittsburgh", "Mt. Lebanon", "Bethel Park", "Monroeville", "McKeesport"],
    Montgomery: ["Norristown", "King of Prussia", "Lansdale", "Abington", "Cheltenham"],
    Delaware: ["Media", "Chester", "Upper Darby", "Springfield", "Drexel Hill"],
    Bucks: ["Doylestown", "Levittown", "Newtown", "Quakertown", "Yardley"],
    Chester: ["West Chester", "Coatesville", "Phoenixville", "West Chester", "Exton"],
    Lancaster: ["Lancaster", "Ephrata", "Lititz", "Manheim"],
    York: ["York", "Hanover", "Red Lion", "Dallastown"],
    Berks: ["Reading", "Wyomissing", "Shillington", "Sinking Spring"],
  },
  RI: {
    Providence: ["Providence", "Cranston", "Pawtucket", "Johnston", "North Providence"],
    Kent: ["Warwick", "Coventry", "West Warwick", "East Greenwich"],
    Newport: ["Newport", "Middletown", "Portsmouth"],
    Washington: ["Westerly", "Narragansett", "South Kingstown", "North Kingstown"],
  },
  SC: {
    Charleston: ["Charleston", "North Charleston", "Mount Pleasant", "Summerville"],
    Greenville: ["Greenville", "Mauldin", "Simpsonville", "Taylors", "Travelers Rest"],
    Richland: ["Columbia", "Forest Acres", "Irmo", "Blythewood"],
    Horry: ["Myrtle Beach", "Conway", "North Myrtle Beach", "Surfside Beach"],
    Spartanburg: ["Spartanburg", "Duncan", "Wellford", "Lyman"],
    Lexington: ["Lexington", "Cayce", "West Columbia", "Irmo"],
  },
  SD: {
    Minnehaha: ["Sioux Falls", "Brandon", "Harrisburg", "Tea"],
    Pennington: ["Rapid City", "Box Elder", "Hill City"],
    Lincoln: ["Sioux Falls", "Harrisburg", "Tea", "Worthing"],
    Brown: ["Aberdeen", "Groton", "Bath"],
  },
  TN: {
    Shelby: ["Memphis", "Bartlett", "Collierville", "Germantown", "Cordova", "Millington"],
    Davidson: ["Nashville", "Goodlettsville", "Belle Meade", "Berry Hill"],
    Knox: ["Knoxville", "Farragut", "Maryville", "Oak Ridge"],
    Hamilton: ["Chattanooga", "East Ridge", "Red Bank", "Soddy-Daisy"],
    Rutherford: ["Murfreesboro", "Smyrna", "La Vergne", "Eagleville"],
    Williamson: ["Franklin", "Brentwood", "Spring Hill", "Nolensville"],
  },
  TX: {
    Harris: ["Houston", "Pasadena", "Baytown", "Spring", "Katy", "Cypress"],
    Dallas: ["Dallas", "Garland", "Irving", "Richardson", "Mesquite", "Carrollton"],
    Tarrant: ["Fort Worth", "Arlington", "Bedford", "Euless", "North Richland Hills", "Grapevine"],
    Bexar: ["San Antonio", "New Braunfels", "Schertz", "Converse", "Live Oak"],
    Travis: ["Austin", "Lago Vista", "Pflugerville", "Lakeway", "Sunset Valley"],
    Collin: ["Plano", "Frisco", "McKinney", "Allen", "Wylie", "Prosper"],
    Denton: ["Denton", "Lewisville", "Flower Mound", "Corinth", "Lake Dallas"],
    El_Paso: ["El Paso", "Socorro", "Horizon City", "Anthony"],
    Hidalgo: ["McAllen", "Edinburg", "Mission", "Pharr"],
    Fort_Bend: ["Sugar Land", "Missouri City", "Richmond", "Rosenberg", "Stafford"],
    Montgomery: ["Conroe", "The Woodlands", "Magnolia", "Montgomery"],
    Williamson: ["Round Rock", "Cedar Park", "Georgetown", "Taylor", "Leander"],
  },
  UT: {
    Salt_Lake: ["Salt Lake City", "West Valley City", "Sandy", "South Jordan", "Murray", "Taylorsville"],
    Utah: ["Provo", "Orem", "Lehi", "Spanish Fork", "Springville", "American Fork"],
    Davis: ["Layton", "Clearfield", "Kaysville", "Bountiful", "Syracuse"],
    Weber: ["Ogden", "Roy", "South Ogden", "Washington Terrace"],
    Washington: ["St. George", "Washington", "Hurricane", "Ivins"],
  },
  VT: {
    Chittenden: ["Burlington", "South Burlington", "Essex", "Colchester", "Winooski"],
    Rutland: ["Rutland", "Castleton", "Poultney"],
    Washington: ["Montpelier", "Barre", "Waterbury"],
    Windsor: ["Hartford", "Springfield", "Woodstock"],
  },
  VA: {
    Fairfax: ["Fairfax", "Vienna", "McLean", "Herndon", "Reston", "Burke"],
    Prince_William: ["Manassas", "Woodbridge", "Dumfries", "Haymarket", "Occoquan"],
    Loudoun: ["Leesburg", "Ashburn", "Sterling", "Purcellville", "Round Hill"],
    Arlington: ["Arlington"],
    Richmond_City: ["Richmond"],
    Virginia_Beach: ["Virginia Beach"],
    Henrico: ["Henrico", "Highland Springs", "Glen Allen", "Sandston"],
    Chesterfield: ["Chesterfield", "Chester", "Midlothian", "Ettrick"],
    Roanoke: ["Roanoke", "Salem", "Vinton"],
  },
  WA: {
    King: ["Seattle", "Bellevue", "Redmond", "Kirkland", "Renton", "Kent", "Auburn"],
    Pierce: ["Tacoma", "Puyallup", "Lakewood", "University Place", "Gig Harbor"],
    Snohomish: ["Everett", "Lynnwood", "Marysville", "Snohomish", "Mukilteo"],
    Spokane: ["Spokane", "Spokane Valley", "Cheney", "Liberty Lake"],
    Clark: ["Vancouver", "Battle Ground", "Camas", "Washougal"],
    Thurston: ["Olympia", "Lacey", "Tumwater", "Yelm"],
    Kitsap: ["Bremerton", "Bainbridge Island", "Port Orchard", "Poulsbo"],
  },
  WV: {
    Kanawha: ["Charleston", "Dunbar", "South Charleston", "St. Albans", "Nitro"],
    Berkeley: ["Martinsburg", "Hedgesville", "Inwood", "Falling Waters"],
    Monongalia: ["Morgantown", "Westover", "Star City"],
    Cabell: ["Huntington", "Milton", "Barboursville"],
  },
  WI: {
    Milwaukee: ["Milwaukee", "Wauwatosa", "West Allis", "Greenfield", "Oak Creek", "Franklin"],
    Dane: ["Madison", "Sun Prairie", "Fitchburg", "Middleton", "Stoughton"],
    Waukesha: ["Waukesha", "Brookfield", "New Berlin", "Muskego", "Pewaukee"],
    Brown: ["Green Bay", "De Pere", "Allouez", "Bellevue"],
    Racine: ["Racine", "Caledonia", "Mount Pleasant", "Sturtevant"],
    Outagamie: ["Appleton", "Kaukauna", "Little Chute", "Kimberly"],
  },
  WY: {
    Laramie: ["Cheyenne", "Pine Bluffs", "Albin", "Burns"],
    Natrona: ["Casper", "Mills", "Evansville", "Bar Nunn"],
    Sweetwater: ["Rock Springs", "Green River", "Superior"],
    Fremont: ["Riverton", "Lander", "Dubois", "Hudson"],
  },
};

export const STAGE_LABELS = {
  qualification: "New Lead",
  takeoff: "AI Takeoff",
  estimating: "Pricing",
  proposal: "Bid Built",
  submitted: "Bid Sent",
  won: "Won",
  lost: "Lost",
};

export const PROJECT_STAGES = [
  { value: "qualification", label: "New Lead" },
  { value: "takeoff", label: "AI Takeoff" },
  { value: "estimating", label: "Pricing" },
  { value: "proposal", label: "Bid Built" },
  { value: "submitted", label: "Bid Sent" },
  { value: "won", label: "Won" },
  { value: "lost", label: "Lost" },
];

export const TRADES = [
  "Access Control Hardware",
  "Access Control Systems",
  "Acoustical Ceilings & Wall Panels",
  "Air & Vapor Barriers",
  "Aquatic / Pool Construction",
  "Asbestos Abatement",
  "Asphalt Paving",
  "Athletic & Recreational Equipment",
  "Athletic Courts & Tracks",
  "Audio/Visual Systems",
  "Awnings & Canopies",
  "Backflow Prevention",
  "Backup Generators",
  "Boilers & Heating Systems",
  "Bridge Construction",
  "Building Automation Systems (BAS)",
  "Cabinetry & Casework",
  "Carpet & Carpet Tile",
  "Ceramic & Porcelain Tile",
  "Chair Lifts & Accessibility Lifts",
  "Chillers & Cooling Towers",
  "Cleanrooms",
  "Cogeneration / CHP",
  "Commercial Doors & Hardware",
  "Commercial Electrical",
  "Commercial Flooring",
  "Commercial Glazing",
  "Commercial HVAC",
  "Commercial Kitchen Equipment",
  "Commercial Plumbing",
  "Commercial Roofing",
  "Concrete Countertops",
  "Concrete Overlays",
  "Concrete Paving & Flatwork",
  "Concrete Placement & Finishing",
  "Concrete Polishing",
  "Concrete Repair & Restoration",
  "Concrete Underlayments",
  "Construction Consulting",
  "Construction Management",
  "Crane & Rigging Services",
  "Dampproofing",
  "Data & Voice Cabling",
  "Decorative Concrete",
  "Demolition",
  "Design-Build Services",
  "Dewatering",
  "Distributed Antenna Systems (DAS)",
  "Docks & Piers",
  "Drilling & Blasting",
  "Dredging",
  "Drywall & Acoustical Ceilings",
  "Earthwork & Excavation",
  "EIFS & Stucco",
  "Emergency & Backup Power",
  "Energy Management Systems",
  "Environmental Remediation",
  "Epoxy Coatings & Flooring",
  "Escalators & Moving Walks",
  "EV Charging Infrastructure",
  "Exhaust & Ventilation Systems",
  "Expansion Joints",
  "Fencing & Gates",
  "Fiber Optic Systems",
  "Fire Alarm Systems",
  "Fire Extinguishers & Cabinets",
  "Fire Pumps",
  "Fire Sprinkler Systems",
  "Fire Suppression Systems (Clean Agent)",
  "Firestopping & Fireproofing",
  "Formwork & Shoring",
  "Fuel Piping",
  "Furniture, Fixtures & Equipment (FF&E)",
  "Gas Distribution",
  "General Contractor",
  "Geothermal Systems",
  "Grading & Site Preparation",
  "Grounding Systems",
  "Gypsum Wallboard",
  "Hardscaping (Pavers, Walkways)",
  "High-Performance Coatings",
  "HVAC Controls",
  "Intrusion Detection",
  "Irrigation Systems",
  "Joists & Metal Deck",
  "Laboratory Equipment",
  "Landscaping & Site Work",
  "Lath & Plaster",
  "Lead Paint Abatement",
  "Lightning Protection",
  "Lighting & Luminaires",
  "Lighting Controls",
  "Manholes & Catch Basins",
  "Marine Construction",
  "Masonry (Brick, Block, Stone)",
  "Mass Notification Systems",
  "Material Handling Equipment",
  "Material Lifts & Dumbwaiters",
  "Medical Equipment",
  "Medical Gas Systems",
  "Metal Decking",
  "Metal Stud Framing",
  "Microgrids",
  "Mold Remediation",
  "Nurse Call Systems",
  "Office Furniture",
  "Ornamental Metal & Railings",
  "Overhead & Sectional Doors",
  "Painting & Finishes",
  "Pavement Marking & Striping",
  "Pest Control & Bird Proofing",
  "Plastic Laminate & Composite Panels",
  "Post-Tensioning",
  "Power Distribution",
  "Power Generation",
  "Precast Concrete",
  "Preconstruction Services",
  "Pre-Engineered Metal Buildings",
  "Process Piping",
  "Public Address & Intercom",
  "Railway Construction",
  "Rebar / Reinforcing Steel",
  "Refractory Masonry",
  "Resilient Flooring (VCT, LVT)",
  "Retaining Walls",
  "Roadway Construction",
  "Roof Coatings & Restoration",
  "Rough Carpentry & Framing",
  "Scaffolding & Shoring",
  "Seawalls & Bulkheads",
  "Selective Demolition",
  "Sheet Metal & Ductwork",
  "Sheet Metal & Roof Flashing",
  "Shotcrete / Gunite",
  "Signage & Wayfinding",
  "Site Furnishings",
  "Soil Remediation",
  "Soil Stabilization",
  "Solar PV Systems",
  "Soundproofing & Acoustic Enclosures",
  "Specialty Finishes",
  "Steel Erection",
  "Storage Shelving",
  "Storm Drainage Systems",
  "Structural Steel",
  "Structure Relocation",
  "Surveying & Layout",
  "Terrazzo",
  "Testing & Inspection Services",
  "Testing, Adjusting & Balancing (TAB)",
  "Thermal Insulation",
  "Tilt-Up Concrete",
  "Toilet Partitions & Accessories",
  "Traffic Control / MOT",
  "Traffic Signals & Signage",
  "Trenching & Shoring",
  "Tuckpointing & Masonry Restoration",
  "Underground Utilities",
  "Vehicle Charging Stations",
  "Video Surveillance / CCTV",
  "Wall Finishes & Wallcoverings",
  "Water & Sewer Lines",
  "Waterproofing",
  "Weatherproofing / Enclosures",
  "Welding & Fabrication",
  "Window Films & Tinting",
  "Window Treatments & Blinds",
];

export const SOURCE_TYPES = [
  { value: "government_portal", label: "Government Portal" },
  { value: "aggregator", label: "Aggregator" },
  { value: "email", label: "Email" },
  { value: "api", label: "API" },
  { value: "manual", label: "Manual" },
];

// Built-in national construction bid sources. These are real, well-known
// portals/aggregators for public and private construction opportunities.
export const BUILTIN_SOURCES = [
  { name: "SAM.gov", url: "https://sam.gov", source_type: "government_portal", jurisdiction: "Federal" },
  { name: "BidNet Direct (State & Local)", url: "https://www.bidnetdirect.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "ConstructConnect", url: "https://www.constructconnect.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "Dodge Construction Network", url: "https://www.construction.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "BidClerk", url: "https://www.bidclerk.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "BuildingConnected (Autodesk)", url: "https://www.buildingconnected.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "iSqFt (ConstructConnect)", url: "https://www.isqft.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "QuestCDN", url: "https://www.questcdn.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "GovernmentBids.com", url: "https://www.governmentbids.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "BidCentral", url: "https://www.bidcentral.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "Cityfeet", url: "https://www.cityfeet.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "PennBid (Pennsylvania)", url: "https://www.pennbid.com", source_type: "government_portal", jurisdiction: "PA" },
  { name: "Texas SmartBuy (Texas)", url: "https://www.txsmartbuy.com", source_type: "government_portal", jurisdiction: "TX" },
  { name: "Cal eProcure (California)", url: "https://www.caleprocure.ca.gov", source_type: "government_portal", jurisdiction: "CA" },
  { name: "NY OGS Procurement", url: "https://www.ogs.ny.gov", source_type: "government_portal", jurisdiction: "NY" },
  { name: "Florida Vendor Bid System", url: "https://vendor.myfloridamarketplace.com", source_type: "government_portal", jurisdiction: "FL" },
  { name: "Georgia Team Georgia Marketplace", url: "https://www.teamgeorgiabid.com", source_type: "government_portal", jurisdiction: "GA" },
  { name: "North Carolina eProcurement", url: "https://www.eprocurement.nc.gov", source_type: "government_portal", jurisdiction: "NC" },
  { name: "Ohio Procurement", url: "https://procure.ohio.gov", source_type: "government_portal", jurisdiction: "OH" },
  { name: "Illinois Bid (Illinois Procurement)", url: "https://www.bid.illinois.gov", source_type: "government_portal", jurisdiction: "IL" },
  { name: "Washington State WEBS", url: "https://www.webs.wa.gov", source_type: "government_portal", jurisdiction: "WA" },
  { name: "Colorado Bid System", url: "https://www.colorado.gov/bids", source_type: "government_portal", jurisdiction: "CO" },
  { name: "Arizona State Procurement Office", url: "https://www.spo.az.gov", source_type: "government_portal", jurisdiction: "AZ" },
  { name: "Virginia eVA", url: "https://www.eva.virginia.gov", source_type: "government_portal", jurisdiction: "VA" },
  { name: "Massachusetts COMMBUYS", url: "https://www.commbuys.com", source_type: "government_portal", jurisdiction: "MA" },
  { name: "New Jersey NJSTART", url: "https://www.njstart.gov", source_type: "government_portal", jurisdiction: "NJ" },
  { name: "Maryland eMaryland Marketplace", url: "https://www.emarylandmarketplace.com", source_type: "government_portal", jurisdiction: "MD" },
  { name: "Michigan SIGMA Vendor Self-Service", url: "https://www.michigan.gov/sigma", source_type: "government_portal", jurisdiction: "MI" },
  { name: "Pennsylvania eMarketplace", url: "https://www.emarketplace.state.pa.us", source_type: "government_portal", jurisdiction: "PA" },
  { name: "Tennessee eBid System", url: "https://www.tn.gov/procurement", source_type: "government_portal", jurisdiction: "TN" },
  { name: "Wisconsin VendorNet", url: "https://www.vendornet.wi.gov", source_type: "government_portal", jurisdiction: "WI" },
  { name: "Minnesota SWIFT", url: "https://www.swift.mn.gov", source_type: "government_portal", jurisdiction: "MN" },
  { name: "Oregon Procurement", url: "https://www.oregon.gov/das/procurement", source_type: "government_portal", jurisdiction: "OR" },
  { name: "Nevada State Purchasing", url: "https://www.nvpurchasing.gov", source_type: "government_portal", jurisdiction: "NV" },
  { name: "Utah State Procurement", url: "https://www.purchasing.utah.gov", source_type: "government_portal", jurisdiction: "UT" },
  { name: "Indiana Procurement Portal", url: "https://www.in.gov/idoa/procurement", source_type: "government_portal", jurisdiction: "IN" },
  { name: "Missouri MoBUYS", url: "https://www.mobuys.mo.gov", source_type: "government_portal", jurisdiction: "MO" },
  { name: "Kentucky eProcurement", url: "https://www.epp.ky.gov", source_type: "government_portal", jurisdiction: "KY" },
  { name: "Louisiana LaPAC", url: "https://wwwprd.doa.louisiana.gov/la", source_type: "government_portal", jurisdiction: "LA" },
  { name: "Alabama State Purchasing", url: "https://www.purchasing.alabama.gov", source_type: "government_portal", jurisdiction: "AL" },
  { name: "South Carolina SCEIS", url: "https://www.sceis.sc.gov", source_type: "government_portal", jurisdiction: "SC" },
  { name: "Oklahoma State Purchasing", url: "https://www.ok.gov/dcs", source_type: "government_portal", jurisdiction: "OK" },
  { name: "Kansas DAS Purchasing", url: "https://www.admin.ks.gov/offices/procurement", source_type: "government_portal", jurisdiction: "KS" },
  { name: "Iowa IowaTAP", url: "https://www.iowatap.com", source_type: "government_portal", jurisdiction: "IA" },
  { name: "Arkansas State Purchasing", url: "https://www.dfa.arkansas.gov/offices/procurement", source_type: "government_portal", jurisdiction: "AR" },
  { name: "New Mexico State Purchasing", url: "https://www.state.nm.us/spd", source_type: "government_portal", jurisdiction: "NM" },
  { name: "Idaho State Purchasing", url: "https://www.purchasing.idaho.gov", source_type: "government_portal", jurisdiction: "ID" },
  { name: "Montana State Procurement", url: "https://www.mt.gov/doa/procurement", source_type: "government_portal", jurisdiction: "MT" },
  { name: "Wyoming State Purchasing", url: "https://www.wyoming.gov/business/purchasing", source_type: "government_portal", jurisdiction: "WY" },
  { name: "Nebraska State Purchasing", url: "https://das.nebraska.gov/materiel", source_type: "government_portal", jurisdiction: "NE" },
  { name: "South Dakota Bureau of Administration", url: "https://bfs.sd.gov/procurement", source_type: "government_portal", jurisdiction: "SD" },
  { name: "North Dakota State Procurement", url: "https://www.nd.gov/procurement", source_type: "government_portal", jurisdiction: "ND" },
  { name: "Delaware Contracting", url: "https://bids.delaware.gov", source_type: "government_portal", jurisdiction: "DE" },
  { name: "Rhode Island Purchasing", url: "https://www.purchasing.ri.gov", source_type: "government_portal", jurisdiction: "RI" },
  { name: "New Hampshire Granite State Purchasing", url: "https://www.gsnh.com", source_type: "government_portal", jurisdiction: "NH" },
  { name: "Vermont State Purchasing", url: "https://www.bgs.vermont.gov/purchasing", source_type: "government_portal", jurisdiction: "VT" },
  { name: "Maine State Purchasing", url: "https://www.maine.gov/dafs/bbm/procurement", source_type: "government_portal", jurisdiction: "ME" },
  { name: "Alaska State Procurement", url: "https://www.doa.alaska.gov/procurement", source_type: "government_portal", jurisdiction: "AK" },
  { name: "Hawaii State Procurement Office", url: "https://www.hawaii.gov/spo", source_type: "government_portal", jurisdiction: "HI" },
  { name: "West Virginia Purchasing", url: "https://www.state.wv.us/admin/purchase", source_type: "government_portal", jurisdiction: "WV" },
  { name: "DC OCP (DC Office of Contracting)", url: "https://ocp.dc.gov", source_type: "government_portal", jurisdiction: "DC" },
  { name: "AGC of America (Associated General Contractors)", url: "https://www.agc.org", source_type: "aggregator", jurisdiction: "National" },
  { name: "ENR (Engineering News-Record) Bid Lists", url: "https://www.enr.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "Blue Book Network", url: "https://www.thebluebook.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "PlanHub", url: "https://www.planhub.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "Procore Construction Network", url: "https://construction.procore.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "BidWell", url: "https://www.bidwell.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "American City & County Bids", url: "https://www.americancityandcounty.com", source_type: "aggregator", jurisdiction: "National" },
  { name: "Onvia (Dun & Bradstreet)", url: "https://www.onvia.com", source_type: "aggregator", jurisdiction: "National" },
];

export function getCounties(stateCode) {
  if (!stateCode) return [];
  const map = STATE_COUNTIES[stateCode];
  return map ? Object.keys(map) : [];
}

export function getCities(stateCode, county) {
  if (!stateCode || !county) return [];
  const map = STATE_COUNTIES[stateCode];
  if (!map || !map[county]) return [];
  return map[county];
}

export function formatJurisdiction(stateCode, county, city) {
  const parts = [];
  if (city) parts.push(city);
  if (county) parts.push(county.replace(/_/g, " "));
  if (stateCode) parts.push(stateCode);
  return parts.join(", ");
}