// Comprehensive scope → system type database with specifications.
// Each scope contains multiple system types, each with its own specs, materials,
// pricing ranges, and identification keywords. The identifySystems() function
// matches project text (descriptions, specs, bid documents) to the correct system
// so the system can accurately identify and price what's being called out.

export const SCOPE_SYSTEMS = {
  "Epoxy Flooring": {
    systems: [
      {
        code: "EF-SOLID",
        name: "Solid Color Epoxy System",
        aliases: ["solid epoxy", "solid color epoxy", "epoxy coating", "epoxy paint", "two-part epoxy", "2-coat epoxy", "epoxy floor coating", "industrial epoxy"],
        description: "Two-coat pigmented epoxy floor coating for industrial, commercial, and garage floors. Smooth, seamless, easy to clean.",
        specifications: {
          preparation: "Mechanical diamond grind or shot blast to CSP-2/3 profile; repair cracks and joints",
          primer: "1 coat epoxy primer at 7-10 mils WFT",
          base: "1 coat pigmented epoxy base coat at 10-14 mils WFT",
          topcoat: "1 coat pigmented epoxy or polyurethane topcoat at 8-10 mils WFT",
          total_thickness: "16-24 mils DFT",
          recoat_window: "12-24 hours between coats",
          full_cure: "7 days for vehicular traffic",
          traffic: "Light foot traffic 24 hrs, heavy traffic 72 hrs",
        },
        materials: [
          { material: "Epoxy Primer", unit: "GAL", coverage: "250-300 SF/GAL" },
          { material: "Epoxy Base Coat Pigmented", unit: "GAL", coverage: "160-200 SF/GAL" },
          { material: "Epoxy or Urethane Topcoat", unit: "GAL", coverage: "250-300 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 4.00,
        typical_price_high: 7.00,
      },
      {
        code: "EF-FLAKE",
        name: "Flake Epoxy Floor System",
        aliases: ["flake epoxy", "chip epoxy", "decorative flake", "vinyl flake", "color chip", "flake floor", "broadcast flake", "epoxy flake", "flake system"],
        description: "Decorative epoxy system with full broadcast vinyl flakes between base coat and clear topcoat. Popular for garages, commercial spaces, and retail.",
        specifications: {
          preparation: "Mechanical diamond grind or shot blast to CSP-2/3; repair cracks, joints, and spalls",
          primer: "1 coat epoxy primer at 8-10 mils WFT",
          base: "1 coat pigmented epoxy base coat at 12-16 mils WFT",
          broadcast: "Full broadcast vinyl flakes 1/4 or 3/8 inch size to refusal while base is wet",
          topcoat: "2 coats clear epoxy or polyaspartic topcoat at 8-10 mils WFT each, scraped between coats",
          total_thickness: "20-30 mils DFT excluding flake build",
          recoat_window: "12-24 hours between coats; scrape flakes after overnight cure",
          full_cure: "7 days for vehicular traffic",
          traffic: "Light foot traffic 24 hrs, vehicular 5-7 days",
        },
        materials: [
          { material: "Epoxy Primer", unit: "GAL", coverage: "250-300 SF/GAL" },
          { material: "Epoxy Base Coat Pigmented", unit: "GAL", coverage: "125-160 SF/GAL" },
          { material: "Vinyl Flakes 1/4 or 3/8 inch", unit: "LB", coverage: "1 LB per 8-10 SF full broadcast" },
          { material: "Clear Epoxy or Polyaspartic Topcoat", unit: "GAL", coverage: "250-300 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 5.50,
        typical_price_high: 9.00,
      },
      {
        code: "EF-METALLIC",
        name: "Metallic Epoxy System",
        aliases: ["metallic epoxy", "metallic floor", "pearlescent epoxy", "3d epoxy", "metallic pigment", "metallic coating"],
        description: "High-end decorative epoxy with metallic pigments creating 3D shimmering effects. Used in showrooms, restaurants, lobbies, and high-end residential.",
        specifications: {
          preparation: "Mechanical diamond grind to CSP-2/3; surface must be very smooth; repair all imperfections",
          primer: "1 coat clear or pigmented epoxy primer at 8-10 mils WFT",
          body: "1-2 coats metallic epoxy with metallic pigment additive at 15-20 mils WFT per coat",
          topcoat: "1-2 coats clear epoxy or polyurethane topcoat at 8-10 mils WFT each",
          total_thickness: "25-40 mils DFT",
          recoat_window: "8-16 hours between coats; manipulate metallic pattern while wet",
          full_cure: "7 days for full chemical resistance",
          traffic: "Light foot traffic 24 hrs, heavy 72 hrs",
        },
        materials: [
          { material: "Epoxy Primer", unit: "GAL", coverage: "250-300 SF/GAL" },
          { material: "Metallic Epoxy Body Coat", unit: "GAL", coverage: "100-160 SF/GAL" },
          { material: "Metallic Pigment Powder", unit: "EA", coverage: "1 unit per 2-3 GAL of epoxy" },
          { material: "Clear Epoxy or Urethane Topcoat", unit: "GAL", coverage: "250-300 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 8.00,
        typical_price_high: 15.00,
      },
      {
        code: "EF-QUARTZ",
        name: "Quartz Epoxy System",
        aliases: ["quartz epoxy", "quartz floor", "epoxy quartz", "colored quartz", "quartz broadcast", "quartz system"],
        description: "Durable slip-resistant epoxy system with colored quartz aggregate broadcast. Used in commercial kitchens, locker rooms, restrooms, and industrial areas.",
        specifications: {
          preparation: "Mechanical diamond grind or shot blast to CSP-2/3",
          primer: "1 coat epoxy primer at 8-10 mils WFT",
          base: "1 coat pigmented epoxy base at 12-16 mils WFT",
          broadcast: "Full broadcast colored quartz 20-40 mesh or 30-50 mesh to refusal",
          topcoat: "1-2 coats clear epoxy sealer at 8-10 mils WFT each",
          total_thickness: "30-40 mils DFT",
          recoat_window: "12-24 hours between coats",
          full_cure: "7 days",
          traffic: "Foot traffic 24 hrs, heavy 72 hrs",
        },
        materials: [
          { material: "Epoxy Primer", unit: "GAL", coverage: "250-300 SF/GAL" },
          { material: "Epoxy Base Coat", unit: "GAL", coverage: "125-160 SF/GAL" },
          { material: "Colored Quartz Aggregate", unit: "LB", coverage: "1 LB per 4-6 SF full broadcast" },
          { material: "Clear Epoxy Sealer", unit: "GAL", coverage: "250-300 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 6.00,
        typical_price_high: 11.00,
      },
      {
        code: "EF-MORTAR",
        name: "Epoxy Mortar System",
        aliases: ["epoxy mortar", "mortar system", "epoxy slurry", "heavy duty epoxy", "troweled epoxy", "epoxy mortar floor"],
        description: "Heavy-duty troweled epoxy mortar system for high-impact and thermal-shock environments. Used in commercial kitchens, manufacturing, and warehouses with heavy loads.",
        specifications: {
          preparation: "Shot blast to CSP-3/4; repair all substrate damage",
          primer: "1 coat epoxy primer at 8-10 mils WFT",
          mortar: "Trowel-applied epoxy mortar epoxy resin plus silica sand at 1/8 to 1/4 inch thickness",
          grout: "1 coat epoxy grout to fill voids in mortar surface",
          topcoat: "1-2 coats pigmented epoxy or urethane topcoat at 8-10 mils WFT each",
          total_thickness: "125-250 mils 1/8 to 1/4 inch",
          recoat_window: "12-24 hours between coats",
          full_cure: "7 days",
          traffic: "Foot traffic 24 hrs, heavy equipment 72 hrs",
        },
        materials: [
          { material: "Epoxy Primer", unit: "GAL", coverage: "250-300 SF/GAL" },
          { material: "Epoxy Mortar Resin", unit: "GAL", coverage: "40-50 SF/GAL at 1/4 inch" },
          { material: "Silica Sand for mortar", unit: "LB", coverage: "Mixed 1:4-1:5 with resin" },
          { material: "Epoxy Grout Coat", unit: "GAL", coverage: "100-160 SF/GAL" },
          { material: "Epoxy or Urethane Topcoat", unit: "GAL", coverage: "250-300 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 9.00,
        typical_price_high: 16.00,
      },
      {
        code: "EF-ESD",
        name: "Anti-Static / ESD Epoxy System",
        aliases: ["anti-static epoxy", "esd epoxy", "conductive epoxy", "static control epoxy", "static dissipative", "esd flooring"],
        description: "Electrostatic dissipative epoxy system for electronics manufacturing, server rooms, and cleanrooms. Conductive primer plus dissipative topcoat with copper grounding strips.",
        specifications: {
          preparation: "Mechanical diamond grind to CSP-2/3; test substrate for moisture",
          conductive_primer: "1 coat conductive epoxy primer at 8-10 mils WFT",
          grounding: "Copper grounding strips at 20 ft on-center, connected to building ground",
          topcoat: "1-2 coats static-dissipative epoxy topcoat at 8-10 mils WFT each",
          total_thickness: "16-24 mils DFT",
          electrical_resistance: "10^6 to 10^9 ohms dissipative range",
          recoat_window: "12-24 hours between coats",
          full_cure: "7 days",
        },
        materials: [
          { material: "Conductive Epoxy Primer", unit: "GAL", coverage: "200-250 SF/GAL" },
          { material: "Copper Grounding Strip", unit: "LF", coverage: "1 LF per 20 SF" },
          { material: "Static-Dissipative Epoxy Topcoat", unit: "GAL", coverage: "250-300 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 7.00,
        typical_price_high: 12.00,
      },
      {
        code: "EF-CLEAR",
        name: "Clear Epoxy Sealer System",
        aliases: ["clear epoxy", "epoxy sealer", "clear coat epoxy", "epoxy topcoat", "clear sealer"],
        description: "Single or two-coat clear epoxy sealer over prepared concrete. Enhances durability and chemical resistance while maintaining natural concrete appearance.",
        specifications: {
          preparation: "Mechanical diamond grind to CSP-2; surface must be clean and dry",
          coats: "1-2 coats clear epoxy at 8-10 mils WFT each",
          total_thickness: "8-20 mils DFT",
          recoat_window: "12-24 hours",
          full_cure: "7 days",
        },
        materials: [
          { material: "Clear Epoxy Sealer", unit: "GAL", coverage: "250-300 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 2.50,
        typical_price_high: 5.00,
      },
      {
        code: "EF-POLY",
        name: "Polyaspartic Flake System",
        aliases: ["polyaspartic", "polyaspartic flake", "polyaspartic coating", "one day epoxy", "fast cure flake", "polyaspartic floor"],
        description: "Fast-curing polyaspartic flake system that can be installed in a single day. UV-stable, will not amber. Premium alternative to traditional epoxy flake.",
        specifications: {
          preparation: "Mechanical diamond grind to CSP-2/3",
          primer: "1 coat polyaspartic primer at 8-10 mils WFT",
          base: "1 coat pigmented polyaspartic base at 12-16 mils WFT with full flake broadcast",
          topcoat: "1-2 coats clear polyaspartic topcoat at 8-10 mils WFT each",
          total_thickness: "20-30 mils DFT",
          recoat_window: "2-4 hours between coats same-day installation possible",
          full_cure: "24 hours for vehicular traffic",
          traffic: "Foot traffic 4-6 hrs, vehicular 24 hrs",
        },
        materials: [
          { material: "Polyaspartic Primer", unit: "GAL", coverage: "250-300 SF/GAL" },
          { material: "Polyaspartic Base Coat Pigmented", unit: "GAL", coverage: "125-160 SF/GAL" },
          { material: "Vinyl Flakes", unit: "LB", coverage: "1 LB per 8-10 SF" },
          { material: "Clear Polyaspartic Topcoat", unit: "GAL", coverage: "250-300 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 6.50,
        typical_price_high: 11.00,
      },
    ],
  },

  "Concrete Polishing": {
    systems: [
      {
        code: "CP-SATIN",
        name: "Satin Polished Concrete 400 Grit",
        aliases: ["satin polish", "400 grit", "satin concrete", "level 2 polish", "honed polish", "400 grit polish"],
        description: "Level 2 polish with 400-grit resin pads. Soft satin sheen, smooth surface, moderate reflectivity. Most common for retail and commercial.",
        specifications: {
          preparation: "Repair cracks, joints, and spalls; clean surface",
          metal_bond: "Grind with 30/70/120 grit metal-bond diamonds",
          resin_bond: "Polish with 100/200/400 grit resin-bond diamonds",
          densifier: "Apply lithium or sodium silicate densifier after 200 grit",
          sealer: "Optional: stain guard or micro-finish sealer",
          grit_level: "400 grit Level 2",
          finish: "Satin sheen, 30-40 degree gloss",
        },
        materials: [
          { material: "Densifier Lithium Silicate", unit: "GAL", coverage: "200-300 SF/GAL" },
          { material: "Metal-Bond Diamonds 30/70/120", unit: "SET", coverage: "3000-5000 SF per set" },
          { material: "Resin-Bond Diamonds 100/200/400", unit: "SET", coverage: "2000-3000 SF per set" },
          { material: "Stain Guard Sealer optional", unit: "GAL", coverage: "500-1000 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 3.50,
        typical_price_high: 6.00,
      },
      {
        code: "CP-GLOSS",
        name: "High Gloss Polished Concrete 800 Grit",
        aliases: ["high gloss", "800 grit", "gloss polish", "level 3 polish", "semi-gloss concrete", "800 grit polish"],
        description: "Level 3 polish with 800-grit resin pads. High gloss, reflective surface. Used in showrooms, retail, and high-traffic commercial.",
        specifications: {
          preparation: "Repair cracks, joints, and spalls; clean surface",
          metal_bond: "Grind with 30/70/120/220 grit metal-bond diamonds",
          resin_bond: "Polish with 100/200/400/800 grit resin-bond diamonds",
          densifier: "Apply densifier after 200 grit and again after 400 grit",
          sealer: "Optional: stain guard or micro-finish sealer",
          grit_level: "800 grit Level 3",
          finish: "High gloss, 50-60 degree gloss",
        },
        materials: [
          { material: "Densifier Lithium Silicate", unit: "GAL", coverage: "200-300 SF/GAL" },
          { material: "Metal-Bond Diamonds 30/70/120/220", unit: "SET", coverage: "3000-5000 SF per set" },
          { material: "Resin-Bond Diamonds 100/200/400/800", unit: "SET", coverage: "1500-2500 SF per set" },
          { material: "Stain Guard Sealer optional", unit: "GAL", coverage: "500-1000 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 4.50,
        typical_price_high: 7.50,
      },
      {
        code: "CP-MIRROR",
        name: "Mirror Finish Polished Concrete 1500+ Grit",
        aliases: ["mirror finish", "1500 grit", "mirror polish", "level 4 polish", "ultra gloss", "1500 grit polish", "3000 grit"],
        description: "Level 4 polish with 1500-3000 grit resin pads. Glass-like mirror finish with maximum reflectivity. Premium finish for high-end spaces.",
        specifications: {
          preparation: "Repair all imperfections; surface must be extremely flat",
          metal_bond: "Grind with 30/70/120/220 grit metal-bond diamonds",
          resin_bond: "Polish with 100/200/400/800/1500/3000 grit resin-bond diamonds",
          densifier: "Apply densifier after 200, 400, and 800 grit",
          sealer: "Apply burnishing pad with stain guard or micro-finish",
          grit_level: "1500-3000 grit Level 4",
          finish: "Mirror finish, 70+ degree gloss",
        },
        materials: [
          { material: "Densifier Lithium Silicate", unit: "GAL", coverage: "200-300 SF/GAL" },
          { material: "Metal-Bond Diamonds 30/70/120/220", unit: "SET", coverage: "3000-5000 SF per set" },
          { material: "Resin-Bond Diamonds 100-3000", unit: "SET", coverage: "1000-2000 SF per set" },
          { material: "Burnishing Pads 1500/3000", unit: "SET", coverage: "2000-3000 SF per set" },
          { material: "Micro-Finish Sealer", unit: "GAL", coverage: "500-1000 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 6.00,
        typical_price_high: 10.00,
      },
      {
        code: "CP-STAINED",
        name: "Stained and Polished Concrete",
        aliases: ["stained polish", "stained concrete", "acid stain", "dye polish", "colored polish", "stained and polished", "integral color polish"],
        description: "Polished concrete with integral color from acid stain or dye applied before polishing. Adds rich, variegated color to the polished surface.",
        specifications: {
          preparation: "Repair cracks and spalls; grind to open surface",
          color: "Apply acid stain reactive or concrete dye non-reactive after 200 grit",
          neutralize: "Neutralize acid stain with ammonia or baking soda solution",
          densifier: "Apply densifier after stain absorption",
          resin_bond: "Polish with 400/800 grit resin-bond diamonds",
          sealer: "Apply stain guard or micro-finish sealer",
          finish: "Colored satin to high gloss depending on grit level",
        },
        materials: [
          { material: "Acid Stain or Concrete Dye", unit: "GAL", coverage: "200-400 SF/GAL" },
          { material: "Densifier Lithium Silicate", unit: "GAL", coverage: "200-300 SF/GAL" },
          { material: "Resin-Bond Diamonds", unit: "SET", coverage: "1500-2500 SF per set" },
          { material: "Stain Guard Sealer", unit: "GAL", coverage: "500-1000 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 5.00,
        typical_price_high: 9.00,
      },
      {
        code: "CP-BURNISH",
        name: "Burnished Concrete",
        aliases: ["burnished", "burnish", "trowel polish", "trowel finish polish", "power trowel polish", "helix polish"],
        description: "Burnished finish achieved with power trowel and densifier on new concrete. No grinding required. Cost-effective option for warehouses and distribution centers.",
        specifications: {
          preparation: "Power trowel new concrete to smooth finish",
          densifier: "Apply densifier during troweling process 2-3 applications",
          burnishing: "Burnish with power trowel or ride-on trowel with pan heads",
          sealer: "Optional: stain guard sealer",
          finish: "Smooth, moderate sheen from trowel burnishing",
        },
        materials: [
          { material: "Densifier Lithium Silicate", unit: "GAL", coverage: "200-300 SF/GAL" },
          { material: "Burnishing Pads", unit: "SET", coverage: "3000-5000 SF per set" },
        ],
        unit: "SF",
        typical_price_low: 2.00,
        typical_price_high: 4.00,
      },
    ],
  },

  "Concrete": {
    systems: [
      {
        code: "CC-SLAB",
        name: "Poured Concrete Slab",
        aliases: ["concrete slab", "poured concrete", "slab on grade", "concrete pour", "flatwork", "concrete floor", "slab"],
        description: "Standard poured-in-place concrete slab on grade. Includes forming, reinforcement, placing, finishing, and curing.",
        specifications: {
          subgrade: "Compact subgrade to 95% Proctor; install vapor barrier if interior",
          reinforcement: "Wire mesh 6x6 W1.4xW1.4 or #4 rebar at 24 inch O.C.",
          thickness: "4 inch residential to 6 inch+ commercial/industrial",
          finish: "Steel trowel, broom, or exposed aggregate per spec",
          curing: "Cure compound or wet curing for 7 days",
          joints: "Saw-cut control joints at 2-3x slab thickness in feet",
        },
        materials: [
          { material: "Concrete 3000-4000 PSI", unit: "CY", coverage: "81 SF at 4 inch per CY" },
          { material: "Wire Mesh 6x6 or Rebar #4", unit: "EA", coverage: "varies by layout" },
          { material: "Vapor Barrier 6-mil poly", unit: "SF", coverage: "1:1 coverage" },
          { material: "Cure Compound", unit: "GAL", coverage: "200-300 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 6.00,
        typical_price_high: 12.00,
      },
      {
        code: "CC-STAMPED",
        name: "Stamped Concrete",
        aliases: ["stamped concrete", "imprinted concrete", "patterned concrete", "decorative concrete", "stamped patio", "stamped driveway"],
        description: "Decorative concrete stamped with patterns to simulate stone, brick, or slate. Includes integral color, release agent, and sealing.",
        specifications: {
          subgrade: "Compact subgrade; install reinforcement",
          reinforcement: "Wire mesh or rebar per design",
          thickness: "4 inch minimum patios/walkways, 6 inch driveways",
          color: "Integral color mixed into concrete plus powder release agent for accent",
          stamping: "Apply stamp mats after initial set; patterns include ashlar slate, cobblestone, brick",
          joints: "Saw-cut or tooled control joints",
          sealing: "Apply acrylic sealer after 28-day cure",
        },
        materials: [
          { material: "Concrete 4000 PSI", unit: "CY", coverage: "81 SF at 4 inch per CY" },
          { material: "Integral Color", unit: "LB", coverage: "1 LB per CY of concrete" },
          { material: "Powder Release Agent", unit: "LB", coverage: "1 LB per 15-20 SF" },
          { material: "Stamp Mats", unit: "EA", coverage: "reusable" },
          { material: "Acrylic Sealer", unit: "GAL", coverage: "200-300 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 12.00,
        typical_price_high: 20.00,
      },
      {
        code: "CC-OVERLAY",
        name: "Concrete Overlay / Micro-Topping",
        aliases: ["concrete overlay", "micro-topping", "skim coat", "resurfacing", "concrete resurfacer", "overlay", "micro finish"],
        description: "Thin cementitious overlay applied over existing concrete to resurface, level, or create decorative finish. Can be stained, polished, or sealed.",
        specifications: {
          preparation: "Mechanical surface prep; repair all cracks and spalls",
          primer: "Apply bonding primer per manufacturer",
          overlay: "Trowel or squeegee overlay at 1/16 to 1/4 inch thickness",
          texture: "Can be smooth, textured, or patterned",
          finish: "Stain, polish, or seal per design",
        },
        materials: [
          { material: "Bonding Primer", unit: "GAL", coverage: "200-300 SF/GAL" },
          { material: "Concrete Overlay Mix", unit: "BAG", coverage: "20-50 SF per 40-lb bag" },
          { material: "Sealer or Stain", unit: "GAL", coverage: "200-300 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 4.00,
        typical_price_high: 9.00,
      },
      {
        code: "CC-REPAIR",
        name: "Concrete Repair",
        aliases: ["concrete repair", "crack repair", "spall repair", "joint repair", "concrete patch", "concrete restoration"],
        description: "Repair of cracks, spalls, joints, and surface defects in existing concrete. Includes epoxy injection, patching, and joint resealing.",
        specifications: {
          crack_repair: "Route and seal cracks with polyurea or epoxy; or inject epoxy for structural cracks",
          spall_repair: "Remove delaminated concrete; apply repair mortar or polymer-modified overlay",
          joint_repair: "Saw-cut and re-seal joints with backer rod and polyurea or silicone sealant",
          surface_prep: "Mechanical prep of repair areas to sound concrete",
        },
        materials: [
          { material: "Epoxy Injection Resin", unit: "EA", coverage: "varies by crack volume" },
          { material: "Polymer-Modified Repair Mortar", unit: "BAG", coverage: "0.5-1 CF per bag" },
          { material: "Joint Sealant Polyurea", unit: "EA", coverage: "varies by joint width" },
          { material: "Backer Rod", unit: "LF", coverage: "1:1" },
        ],
        unit: "SF",
        typical_price_low: 3.00,
        typical_price_high: 15.00,
      },
    ],
  },

  "Painting": {
    systems: [
      {
        code: "PT-INT-WALL",
        name: "Interior Wall Paint System",
        aliases: ["interior paint", "wall paint", "latex paint", "interior latex", "wall coating", "drywall paint"],
        description: "Standard interior wall painting system: primer plus 2 coats latex paint on properly prepared drywall or plaster.",
        specifications: {
          preparation: "Patch and sand imperfections; spot-prime repairs; clean surfaces",
          primer: "1 coat PVA or acrylic primer on bare drywall",
          finish: "2 coats interior latex paint eggshell, satin, or semi-gloss per spec",
          mil_thickness: "3-4 mils DFT per coat",
        },
        materials: [
          { material: "Interior Primer", unit: "GAL", coverage: "300-400 SF/GAL" },
          { material: "Interior Latex Paint", unit: "GAL", coverage: "350-400 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 1.50,
        typical_price_high: 3.50,
      },
      {
        code: "PT-EXT",
        name: "Exterior Paint System",
        aliases: ["exterior paint", "exterior latex", "exterior coating", "siding paint", "facade paint"],
        description: "Exterior wall painting system with moisture-resistant primer and durable exterior-grade paint.",
        specifications: {
          preparation: "Power wash; scrape loose paint; caulk gaps; prime bare areas",
          primer: "1 coat exterior acrylic primer on bare surfaces",
          finish: "2 coats exterior acrylic latex paint",
          mil_thickness: "4-5 mils DFT per coat",
        },
        materials: [
          { material: "Exterior Primer", unit: "GAL", coverage: "300-400 SF/GAL" },
          { material: "Exterior Latex Paint", unit: "GAL", coverage: "300-400 SF/GAL per coat" },
          { material: "Caulk", unit: "EA", coverage: "varies" },
        ],
        unit: "SF",
        typical_price_low: 2.00,
        typical_price_high: 5.00,
      },
      {
        code: "PT-ELAST",
        name: "Elastomeric Coating System",
        aliases: ["elastomeric", "elastomeric coating", "elastomeric paint", "waterproof coating", "masonry coating"],
        description: "Heavy-body elastomeric coating for masonry, stucco, and concrete exteriors. Bridges hairline cracks and provides waterproofing.",
        specifications: {
          preparation: "Power wash; repair cracks with elastomeric patch; prime bare areas",
          primer: "1 coat masonry primer if needed",
          finish: "2 coats elastomeric coating at 10-15 mils WFT per coat",
          mil_thickness: "15-20 mils DFT total",
        },
        materials: [
          { material: "Masonry Primer", unit: "GAL", coverage: "250-350 SF/GAL" },
          { material: "Elastomeric Coating", unit: "GAL", coverage: "60-100 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 3.00,
        typical_price_high: 6.00,
      },
      {
        code: "PT-INDUSTRIAL",
        name: "Industrial Epoxy Paint System",
        aliases: ["epoxy paint", "industrial paint", "epoxy coating", "tank coating", "structural steel paint", "industrial coating"],
        description: "Two-component epoxy coating system for steel, concrete, and industrial surfaces. High chemical and abrasion resistance.",
        specifications: {
          preparation: "SSPC-SP6 commercial blast or SSPC-SP10 near-white blast for steel; CSP-2/3 for concrete",
          primer: "1 coat zinc-rich or epoxy primer at 3-4 mils DFT",
          intermediate: "1 coat epoxy intermediate at 4-6 mils DFT",
          topcoat: "1 coat polyurethane topcoat at 2-3 mils DFT",
          total_thickness: "10-15 mils DFT",
        },
        materials: [
          { material: "Epoxy or Zinc Primer", unit: "GAL", coverage: "200-300 SF/GAL" },
          { material: "Epoxy Intermediate Coat", unit: "GAL", coverage: "150-250 SF/GAL" },
          { material: "Polyurethane Topcoat", unit: "GAL", coverage: "250-350 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 4.00,
        typical_price_high: 10.00,
      },
      {
        code: "PT-INTUMESCENT",
        name: "Intumescent Fireproofing System",
        aliases: ["intumescent", "fireproofing", "fire rated paint", "intumescent paint", "fire protection coating"],
        description: "Intumescent coating that expands under fire to protect structural steel. Rated for 1-3 hour fire ratings.",
        specifications: {
          preparation: "SSPC-SP6 blast cleaning; apply primer if required",
          primer: "1 coat compatible primer at 2-3 mils DFT",
          intumescent: "Multiple coats intumescent at 60-250 mils WFT depending on fire rating",
          topcoat: "1 coat compatible topcoat for weather protection exterior",
          fire_rating: "1, 2, or 3 hour rating per design",
        },
        materials: [
          { material: "Primer compatible", unit: "GAL", coverage: "250-350 SF/GAL" },
          { material: "Intumescent Coating", unit: "GAL", coverage: "4-16 SF/GAL per coat varies by rating" },
          { material: "Topcoat if required", unit: "GAL", coverage: "200-300 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 5.00,
        typical_price_high: 20.00,
      },
    ],
  },

  "Flooring": {
    systems: [
      {
        code: "FL-LVT",
        name: "Luxury Vinyl Tile LVT/LVP",
        aliases: ["lvt", "lvp", "luxury vinyl", "vinyl plank", "vinyl tile", "luxury vinyl tile", "luxury vinyl plank"],
        description: "Click-lock or glue-down luxury vinyl tile/plank flooring. Waterproof, durable, available in wood and stone looks.",
        specifications: {
          preparation: "Subfloor must be flat within 3/16 inch in 10 ft; clean and dry",
          underlayment: "Self-leveling or patch if needed; moisture test if on-grade",
          installation: "Glue-down or floating click-lock per product",
          adhesive: "For glue-down: pressure-sensitive or hard-set adhesive",
          transitions: "T-moldings, reducers, and end caps at doorways",
        },
        materials: [
          { material: "LVT/LVP Flooring", unit: "SF", coverage: "1:1 plus 5-10% waste" },
          { material: "Flooring Adhesive glue-down", unit: "GAL", coverage: "150-200 SF/GAL" },
          { material: "Underlayment/Patch", unit: "BAG", coverage: "varies" },
          { material: "Transition Strips", unit: "LF", coverage: "as needed" },
        ],
        unit: "SF",
        typical_price_low: 4.00,
        typical_price_high: 9.00,
      },
      {
        code: "FL-CARPET-TILE",
        name: "Carpet Tile System",
        aliases: ["carpet tile", "carpet squares", "modular carpet", "tile carpet", "commercial carpet tile"],
        description: "Modular carpet tiles for commercial spaces. Glue-down or tackifier installation. Easy to replace damaged tiles.",
        specifications: {
          preparation: "Subfloor must be clean, dry, and flat; moisture test if on-grade",
          adhesive: "Pressure-sensitive adhesive or tackifier for releasable installation",
          installation: "Quarter-turn, monolithic, or ashlar pattern per design",
          pattern: "Arrow direction must be consistent",
        },
        materials: [
          { material: "Carpet Tile 18x18 or 24x24", unit: "SF", coverage: "1:1 plus 5% waste" },
          { material: "Pressure-Sensitive Adhesive", unit: "GAL", coverage: "150-200 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 3.50,
        typical_price_high: 7.00,
      },
      {
        code: "FL-SHEET-VINYL",
        name: "Sheet Vinyl Flooring",
        aliases: ["sheet vinyl", "vinyl sheet", "linoleum", "sheet flooring", "vct", "vinyl composition tile"],
        description: "Seamless sheet vinyl or VCT for commercial and institutional spaces. Heat-welded seams for sheet vinyl.",
        specifications: {
          preparation: "Subfloor must be smooth; patch and level as needed",
          underlayment: "1/4 inch plywood underlayment if subfloor is not smooth",
          adhesive: "Full-spread adhesive for sheet vinyl; acrylic adhesive for VCT",
          seams: "Heat-welded seams for sheet vinyl; grout for VCT",
          finish: "3-4 coats floor finish for VCT",
        },
        materials: [
          { material: "Sheet Vinyl or VCT", unit: "SF", coverage: "1:1 plus 5% waste" },
          { material: "Flooring Adhesive", unit: "GAL", coverage: "150-200 SF/GAL" },
          { material: "Plywood Underlayment if needed", unit: "EA", coverage: "32 SF per 4x8 sheet" },
          { material: "Floor Finish VCT", unit: "GAL", coverage: "2000-3000 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 3.00,
        typical_price_high: 7.00,
      },
      {
        code: "FL-HARDWOOD",
        name: "Hardwood Flooring System",
        aliases: ["hardwood", "hardwood floor", "wood floor", "engineered wood", "solid hardwood", "wood flooring"],
        description: "Solid or engineered hardwood flooring with nail-down, glue-down, or floating installation. Includes sanding and finishing for unfinished.",
        specifications: {
          preparation: "Subfloor must be flat within 3/16 inch in 10 ft; moisture test",
          underlayment: "Rosin paper or moisture barrier per installation type",
          installation: "Nail-down solid, glue-down engineered, or floating click-lock",
          sanding: "For unfinished: sand with 36/60/80/100 grit; apply 3 coats polyurethane",
          finish: "Water-based or oil-based polyurethane; 3 coats",
        },
        materials: [
          { material: "Hardwood Flooring", unit: "SF", coverage: "1:1 plus 5-10% waste" },
          { material: "Underlayment/Moisture Barrier", unit: "SF", coverage: "1:1" },
          { material: "Flooring Nails or Adhesive", unit: "EA", coverage: "varies" },
          { material: "Polyurethane Finish unfinished", unit: "GAL", coverage: "500-600 SF/GAL per coat" },
        ],
        unit: "SF",
        typical_price_low: 8.00,
        typical_price_high: 18.00,
      },
    ],
  },

  "Tile": {
    systems: [
      {
        code: "TL-PORCELAIN",
        name: "Porcelain Floor Tile System",
        aliases: ["porcelain tile", "porcelain floor", "floor tile", "porcelain", "rectified tile", "large format tile"],
        description: "Porcelain floor tile installation with thinset mortar, grout, and sealer. Includes large-format and rectified tile.",
        specifications: {
          preparation: "Subfloor must be flat within 1/8 inch in 10 ft; deflection rating L/360 minimum",
          membrane: "Crack isolation membrane if over concrete; cement board over wood",
          thinset: "Modified thinset mortar; large-format tile requires LFT thinset",
          grout: "Sanded grout for joints >1/8 inch; unsanded for <1/8 inch; epoxy grout for wet areas",
          sealer: "Penetrating sealer for natural stone; grout sealer for all",
          expansion: "Expansion joints at 24-36 ft per TCNA guidelines",
        },
        materials: [
          { material: "Porcelain Tile", unit: "SF", coverage: "1:1 plus 10-15% waste" },
          { material: "Thinset Mortar LFT for large format", unit: "BAG", coverage: "75-100 SF per 50-lb bag" },
          { material: "Grout Sanded or Epoxy", unit: "BAG", coverage: "100-200 SF per 25-lb bag" },
          { material: "Crack Isolation Membrane if needed", unit: "SF", coverage: "1:1" },
          { material: "Grout Sealer", unit: "GAL", coverage: "500-1000 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 8.00,
        typical_price_high: 18.00,
      },
      {
        code: "TL-CERAMIC-WALL",
        name: "Ceramic Wall Tile System",
        aliases: ["ceramic tile", "wall tile", "ceramic wall", "bathroom tile", "shower tile", "backsplash tile"],
        description: "Ceramic wall tile for bathrooms, showers, and backsplashes. Includes waterproofing for wet areas.",
        specifications: {
          preparation: "Substrate must be clean and flat; cement board or waterproof backer in wet areas",
          waterproofing: "Liquid or sheet waterproofing membrane in showers per TCNA",
          thinset: "Modified thinset mortar; mastic for dry walls",
          grout: "Unsanded grout for joints <1/8 inch; sanded for >1/8 inch",
          sealer: "Grout sealer after 72-hour cure",
        },
        materials: [
          { material: "Ceramic Wall Tile", unit: "SF", coverage: "1:1 plus 10% waste" },
          { material: "Cement Board or Waterproof Backer", unit: "EA", coverage: "32 SF per 4x8 sheet" },
          { material: "Waterproofing Membrane wet areas", unit: "GAL", coverage: "100-150 SF/GAL" },
          { material: "Thinset or Mastic", unit: "BAG", coverage: "75-100 SF per 50-lb bag" },
          { material: "Grout Unsanded", unit: "BAG", coverage: "100-200 SF per 25-lb bag" },
        ],
        unit: "SF",
        typical_price_low: 7.00,
        typical_price_high: 15.00,
      },
      {
        code: "TL-STONE",
        name: "Natural Stone Tile System",
        aliases: ["stone tile", "marble tile", "granite tile", "travertine tile", "slate tile", "natural stone"],
        description: "Natural stone tile installation requiring special handling, sealing, and grouting techniques.",
        specifications: {
          preparation: "Subfloor must be very flat; stone is unforgiving of substrate variations",
          thinset: "White thinset modified to prevent bleed-through; LFT for large format",
          sealing: "Pre-seal stone before grouting to prevent staining; seal again after grout",
          grout: "Unsanded or epoxy grout; match grout color to stone",
          finish: "Honed, polished, or tumbled per stone type",
        },
        materials: [
          { material: "Natural Stone Tile", unit: "SF", coverage: "1:1 plus 15% waste" },
          { material: "White Thinset Mortar", unit: "BAG", coverage: "75-100 SF per 50-lb bag" },
          { material: "Stone Sealer pre-grout", unit: "GAL", coverage: "200-400 SF/GAL" },
          { material: "Grout Unsanded or Epoxy", unit: "BAG", coverage: "100-200 SF per 25-lb bag" },
          { material: "Final Stone Sealer", unit: "GAL", coverage: "200-400 SF/GAL" },
        ],
        unit: "SF",
        typical_price_low: 12.00,
        typical_price_high: 25.00,
      },
    ],
  },

  "Roofing": {
    systems: [
      {
        code: "RF-ARCH",
        name: "Architectural Shingle Roof",
        aliases: ["architectural shingles", "dimensional shingles", "laminated shingles", "asphalt shingles", "composition shingles"],
        description: "Architectural dimensional asphalt shingle roof system with underlayment, flashing, and ventilation.",
        specifications: {
          preparation: "Remove old roofing; inspect and repair deck; install drip edge",
          underlayment: "1 layer synthetic or 30-lb felt underlayment; ice and water shield in valleys and eaves",
          shingles: "Architectural shingles 30-50 year warranty; 3 bundles per square",
          flashing: "Step flashing at walls, valley flashing, pipe boots, and drip edge",
          ventilation: "Ridge vent or box vents per attic ventilation requirements",
          fastening: "4-6 nails per shingle per wind rating",
        },
        materials: [
          { material: "Architectural Shingles", unit: "SQ", coverage: "100 SF per square" },
          { material: "Synthetic Underlayment", unit: "SQ", coverage: "100 SF per roll" },
          { material: "Ice and Water Shield", unit: "SQ", coverage: "100 SF per roll" },
          { material: "Drip Edge", unit: "LF", coverage: "10 LF per piece" },
          { material: "Roofing Nails", unit: "LB", coverage: "varies" },
          { material: "Ridge Vent", unit: "LF", coverage: "as needed" },
        ],
        unit: "SF",
        typical_price_low: 4.00,
        typical_price_high: 8.00,
      },
      {
        code: "RF-TPO",
        name: "TPO Roofing System",
        aliases: ["tpo", "thermoplastic polyolefin", "tpo membrane", "single ply tpo", "white membrane roof"],
        description: "Thermoplastic Polyolefin TPO single-ply membrane roof for flat/low-slope commercial roofs. Heat-welded seams.",
        specifications: {
          preparation: "Install cover board polyiso or gypsum over deck; recover board if reroofing",
          insulation: "Polyiso insulation board at R-value per energy code",
          membrane: "60-mil or 80-mil TPO membrane; mechanically fastened or fully adhered",
          seams: "Heat-welded seams with 1.5 inch minimum overlap; probe all seams",
          flashing: "Prefabricated TPO flashings at penetrations, curbs, and walls",
          warranty: "15-30 year manufacturer warranty",
        },
        materials: [
          { material: "TPO Membrane 60 or 80 mil", unit: "SF", coverage: "1:1 plus 10% waste" },
          { material: "Polyiso Insulation", unit: "SF", coverage: "1:1" },
          { material: "Cover Board Gypsum or HD", unit: "SF", coverage: "1:1" },
          { material: "Fasteners and Plates", unit: "EA", coverage: "1 per 2-3 SF mech attached" },
          { material: "TPO Flashing Accessories", unit: "EA", coverage: "varies" },
        ],
        unit: "SF",
        typical_price_low: 5.00,
        typical_price_high: 10.00,
      },
      {
        code: "RF-METAL",
        name: "Standing Seam Metal Roof",
        aliases: ["standing seam", "metal roof", "metal roofing", "standing seam metal", "steel roof", "metal panels"],
        description: "Standing seam metal panel roof with concealed fasteners. Premium durability and aesthetics.",
        specifications: {
          preparation: "Solid deck or skip sheathing per panel type; underlayment required",
          underlayment: "Synthetic underlayment or high-temp underlayment",
          panels: "24-gauge standing seam panels; clip-fastened for thermal movement",
          flashing: "Pre-formed metal flashing at ridges, valleys, eaves, and penetrations",
          clips: "Sliding clips for thermal expansion/contraction",
        },
        materials: [
          { material: "Standing Seam Metal Panels 24ga", unit: "SF", coverage: "1:1 plus 5% waste" },
          { material: "High-Temp Underlayment", unit: "SQ", coverage: "100 SF per roll" },
          { material: "Panel Clips", unit: "EA", coverage: "1 per 2-3 SF" },
          { material: "Metal Flashing Kit", unit: "EA", coverage: "varies" },
        ],
        unit: "SF",
        typical_price_low: 8.00,
        typical_price_high: 16.00,
      },
    ],
  },

  "Drywall": {
    systems: [
      {
        code: "DW-STANDARD",
        name: "Standard Drywall System",
        aliases: ["drywall", "sheetrock", "gypsum board", "wallboard", "standard drywall", "1/2 drywall"],
        description: "Standard 1/2 or 5/8 inch drywall installation with metal or wood framing, taping, and finishing.",
        specifications: {
          framing: "Metal studs 16 or 24 inch O.C. or wood framing; resilient channel for sound",
          board: "1/2 inch for walls 24 inch O.C. requires 5/8; 1/2 or 5/8 inch for ceilings",
          fastening: "Screws at 12 inch O.C. walls, 8 inch O.C. ceilings",
          taping: "Paper or mesh tape with joint compound; 3 coats - bed, fill, skim",
          finish: "Level 1-5 per spec; Level 4 standard; Level 5 for high-gloss paint",
          corners: "Paper-faced corner bead or vinyl bead",
        },
        materials: [
          { material: 'Drywall Sheet 1/2 inch 4x8', unit: "EA", coverage: "32 SF per sheet" },
          { material: 'Drywall Sheet 5/8 inch 4x8', unit: "EA", coverage: "32 SF per sheet" },
          { material: 'Metal Stud 2-1/2 inch 25GA', unit: "EA", coverage: "1 per 16 or 24 inch O.C." },
          { material: "Joint Compound", unit: "EA", coverage: "5 GAL per 400-500 SF" },
          { material: "Paper Tape", unit: "EA", coverage: "500 LF per roll" },
          { material: "Corner Bead", unit: "LF", coverage: "1:1" },
          { material: 'Drywall Screws 1-1/4 inch', unit: "LB", coverage: "1 LB per 200 SF" },
        ],
        unit: "SF",
        typical_price_low: 2.50,
        typical_price_high: 5.00,
      },
      {
        code: "DW-FIRE",
        name: "Fire-Rated Drywall System Type X",
        aliases: ["type x", "fire rated drywall", "firecode", "5/8 type x", "fire resistant drywall", "fire rated wall"],
        description: "5/8 inch Type X fire-rated drywall for 1-2 hour rated assemblies. Includes required layering and joint compounds.",
        specifications: {
          framing: "Metal or wood framing per UL assembly; resilient channel if required",
          board: "5/8 inch Type X for 1-hour; double 5/8 inch Type X for 2-hour",
          fastening: "Screws per UL assembly; stagger joints on double-layer",
          taping: "Fire-rated joint compound; 3 coats minimum",
          finish: "Level 3-4 per spec; must maintain fire rating integrity",
          assembly: "Must follow specific UL or GA assembly for rating",
        },
        materials: [
          { material: 'Type X Drywall 5/8 inch 4x8', unit: "EA", coverage: "32 SF per sheet" },
          { material: "Fire-Rated Joint Compound", unit: "EA", coverage: "5 GAL per 400 SF" },
          { material: "Paper Tape", unit: "EA", coverage: "500 LF per roll" },
          { material: 'Drywall Screws 1-5/8 inch', unit: "LB", coverage: "1 LB per 150 SF" },
        ],
        unit: "SF",
        typical_price_low: 3.50,
        typical_price_high: 7.00,
      },
      {
        code: "DW-MOISTURE",
        name: "Moisture-Resistant Drywall Green Board",
        aliases: ["green board", "moisture resistant drywall", "greenboard", "bathroom drywall", "wet area drywall"],
        description: "Moisture-resistant drywall for bathrooms, kitchens, and high-humidity areas. Green paper facing.",
        specifications: {
          framing: "Standard framing; cement board in direct wet areas",
          board: "1/2 or 5/8 inch green board; cement board in tub/shower surrounds",
          fastening: "Corrosion-resistant screws",
          taping: "Standard joint compound; moisture-resistant compound in wet areas",
          finish: "Level 4; primer and paint with moisture-resistant paint",
        },
        materials: [
          { material: 'Green Board 1/2 inch 4x8', unit: "EA", coverage: "32 SF per sheet" },
          { material: 'Cement Board 1/2 inch 3x5', unit: "EA", coverage: "15 SF per sheet wet areas" },
          { material: "Joint Compound", unit: "EA", coverage: "5 GAL per 400-500 SF" },
          { material: "Paper Tape", unit: "EA", coverage: "500 LF per roll" },
        ],
        unit: "SF",
        typical_price_low: 3.00,
        typical_price_high: 6.00,
      },
    ],
  },

  "Insulation": {
    systems: [
      {
        code: "IN-BATT",
        name: "Fiberglass Batt Insulation",
        aliases: ["fiberglass batt", "batt insulation", "roll insulation", "fiberglass roll", "batt", "pink insulation", "faced batt"],
        description: "Faced or unfaced fiberglass batt insulation in walls, floors, and ceilings. Pre-cut to standard stud cavities.",
        specifications: {
          installation: "Friction-fit between studs/joists; faced batts with vapor barrier toward conditioned space",
          r_value: "R-13 2x4, R-19 2x6, R-30 floors, R-38+ ceilings",
          vapor_barrier: "Kraft or foil facing acts as vapor retarder; separate poly vapor barrier if unfaced",
          air_sealing: "Seal gaps with spray foam; do not compress batts",
        },
        materials: [
          { material: "Fiberglass Batt R-13, R-19, R-30", unit: "EA", coverage: "varies by size" },
          { material: "Spray Foam gap sealing", unit: "EA", coverage: "varies" },
        ],
        unit: "SF",
        typical_price_low: 1.00,
        typical_price_high: 2.50,
      },
      {
        code: "IN-SPRAY-OPEN",
        name: "Open-Cell Spray Foam",
        aliases: ["open cell spray foam", "open cell foam", "spray foam open", "half pound foam", "oc spray foam"],
        description: "Open-cell half-pound spray foam insulation. Expands to fill cavities, provides air sealing. R-3.6 to R-4 per inch.",
        specifications: {
          application: "Spray into wall/ceiling cavities; expands 100x; trim flush",
          r_value: "R-3.6 to R-4.0 per inch",
          thickness: "Full cavity depth typically 3.5 to 5.5 inch",
          vapor: "Vapor permeable; requires separate vapor barrier in cold climates",
          air_barrier: "Acts as air barrier at 3.5 inch thickness",
        },
        materials: [
          { material: "Open-Cell Spray Foam Kit", unit: "EA", coverage: "varies by kit 600-1200 BF" },
        ],
        unit: "SF",
        typical_price_low: 2.00,
        typical_price_high: 4.00,
      },
      {
        code: "IN-SPRAY-CLOSED",
        name: "Closed-Cell Spray Foam",
        aliases: ["closed cell spray foam", "closed cell foam", "spray foam closed", "two pound foam", "cc spray foam", "closed cell"],
        description: "Closed-cell two-pound spray foam. High R-value, acts as vapor barrier and air barrier. R-6 to R-7 per inch.",
        specifications: {
          application: "Spray into cavities; expands 30-50x; trim flush",
          r_value: "R-6.0 to R-7.0 per inch",
          thickness: "2 to 4 inch typical; 2 inch acts as vapor barrier",
          vapor_barrier: "Acts as vapor barrier at 2 inch thickness",
          air_barrier: "Acts as air barrier at 1 inch thickness",
          structural: "Adds racking strength to walls",
        },
        materials: [
          { material: "Closed-Cell Spray Foam Kit", unit: "EA", coverage: "varies by kit 200-600 BF" },
        ],
        unit: "SF",
        typical_price_low: 3.50,
        typical_price_high: 7.00,
      },
    ],
  },

  "Masonry": {
    systems: [
      {
        code: "MA-BRICK",
        name: "Brick Veneer System",
        aliases: ["brick veneer", "brick wall", "brick masonry", "brick facade", "brick siding", "brick"],
        description: "Brick veneer wall system with weather-resistant barrier, air space, flashing, and weep holes.",
        specifications: {
          backup: "Wood or steel stud framing with sheathing; WRB over sheathing",
          air_space: "1 inch minimum air space between brick and backup",
          flashing: "Through-wall flashing at base, openings, and intersections; weep holes at 24 inch O.C.",
          mortar: "Type N or S mortar; tooled joints concave or weather",
          ties: "Corrugated or adjustable veneer ties at 24 inch O.C. horizontal, 16 inch vertical",
          lintels: "Steel lintels over openings; expansion joints at 25 ft O.C.",
        },
        materials: [
          { material: "Modular Brick", unit: "EA", coverage: "6.75 bricks per SF" },
          { material: "Mortar Mix Type N or S", unit: "BAG", coverage: "35-40 SF per 80-lb bag" },
          { material: "Veneer Ties", unit: "EA", coverage: "1 per 2.67 SF" },
          { material: "Flashing and Weep Vents", unit: "LF", coverage: "as needed" },
          { material: "Steel Lintels", unit: "LF", coverage: "as needed" },
        ],
        unit: "SF",
        typical_price_low: 15.00,
        typical_price_high: 30.00,
      },
      {
        code: "MA-CMU",
        name: "CMU Block Wall System",
        aliases: ["cmu", "concrete block", "cinder block", "block wall", "concrete masonry unit", "block masonry"],
        description: "Concrete masonry unit CMU wall with mortar, reinforcement, and grout fill as required.",
        specifications: {
          foundation: "Reinforced concrete footing; dowel vertical rebar",
          block: "8x8x16 or 12x8x16 CMU; standard or architectural finish",
          mortar: "Type S mortar for structural walls; tooled joints",
          reinforcement: "Vertical rebar at 24-48 inch O.C.; horizontal joint reinforcement at 16 inch O.C.",
          grout: "Grout fill cells with rebar; solid grout if high-lift",
          finish: "Paint, parging, or exposed per design",
        },
        materials: [
          { material: "CMU Block 8x8x16", unit: "EA", coverage: "1.125 blocks per SF" },
          { material: "Mortar Mix Type S", unit: "BAG", coverage: "35-40 SF per 80-lb bag" },
          { material: "Rebar #4 or #5", unit: "EA", coverage: "varies by spacing" },
          { material: "Grout Fill", unit: "CY", coverage: "0.0025 CY per SF per cell" },
          { material: "Joint Reinforcement", unit: "LF", coverage: "1 per 16 inch vertical" },
        ],
        unit: "SF",
        typical_price_low: 12.00,
        typical_price_high: 25.00,
      },
      {
        code: "MA-STONE",
        name: "Stone Veneer System",
        aliases: ["stone veneer", "stone wall", "stone facade", "manufactured stone", "cultured stone", "stone siding"],
        description: "Manufactured or natural stone veneer over framed or masonry backup with mortar and flashing.",
        specifications: {
          backup: "Framed wall with sheathing and 2 layers WRB; or masonry backup",
          lath: "Galvanized metal lath or scratch coat over WRB",
          scratch_coat: "Type S mortar scratch coat over lath; let cure",
          stone: "Manufactured or natural thin stone; mortar-set individual pieces",
          mortar: "Type S or N mortar; point joints after setting",
          flashing: "Through-wall flashing at base and openings",
        },
        materials: [
          { material: "Stone Veneer Manufactured or Natural", unit: "SF", coverage: "1:1 plus 10% waste" },
          { material: "Metal Lath", unit: "SF", coverage: "1:1" },
          { material: "Mortar Type S", unit: "BAG", coverage: "30-35 SF per 80-lb bag" },
          { material: "WRB 2 layers", unit: "SF", coverage: "1:1 x 2" },
        ],
        unit: "SF",
        typical_price_low: 15.00,
        typical_price_high: 35.00,
      },
    ],
  },

  "Carpentry": {
    systems: [
      {
        code: "CR-ROUGH",
        name: "Rough Carpentry / Framing",
        aliases: ["rough carpentry", "framing", "wood framing", "rough framing", "stick framing", "carpentry framing"],
        description: "Wood framing for walls, floors, and roofs including plates, studs, joists, and rafters.",
        specifications: {
          plates: "Treated sill plate on foundation; double top plate",
          studs: "2x4 or 2x6 at 16 or 24 inch O.C.; fire-block as required",
          joists: "I-joists or dimensional lumber per span; rim joist",
          sheathing: "1/2 or 5/8 inch OSB or plywood wall sheathing; 3/4 inch subfloor",
          headers: "Engineered LVL or dimensional headers over openings",
          bracing: "Let-in bracing or structural sheathing for shear",
        },
        materials: [
          { material: "2x4 or 2x6 Lumber", unit: "EA", coverage: "varies by layout" },
          { material: "I-Joists or Dimensional Joists", unit: "EA", coverage: "varies by span" },
          { material: 'OSB Sheathing 7/16 inch', unit: "EA", coverage: "32 SF per 4x8" },
          { material: 'OSB Subfloor 3/4 inch', unit: "EA", coverage: "32 SF per 4x8" },
          { material: "Framing Nails", unit: "LB", coverage: "varies" },
        ],
        unit: "SF",
        typical_price_low: 5.00,
        typical_price_high: 12.00,
      },
      {
        code: "CR-FINISH",
        name: "Finish Carpentry / Trim",
        aliases: ["finish carpentry", "trim", "trim work", "baseboard", "casing", "crown molding", "finish work"],
        description: "Interior finish carpentry including baseboard, casing, crown molding, and other architectural trim.",
        specifications: {
          baseboard: "Base shoe and baseboard; cope inside corners",
          casing: "Door and window casing; miter or butt joints per style",
          crown: "Crown molding; cope inside corners; scarf joints",
          material: "MDF, pine, or poplar; pre-primed for paint; stain-grade for natural finish",
          installation: "Nail with finish nails; fill holes; caulk gaps",
        },
        materials: [
          { material: "Baseboard various profiles", unit: "LF", coverage: "1:1 plus 10% waste" },
          { material: "Door/Window Casing", unit: "LF", coverage: "1:1 plus 10% waste" },
          { material: "Crown Molding", unit: "LF", coverage: "1:1 plus 15% waste" },
          { material: "Finish Nails", unit: "EA", coverage: "varies" },
          { material: "Caulk", unit: "EA", coverage: "varies" },
        ],
        unit: "LF",
        typical_price_low: 2.50,
        typical_price_high: 8.00,
      },
    ],
  },

  "Demolition": {
    systems: [
      {
        code: "DM-INTERIOR",
        name: "Interior Demolition",
        aliases: ["interior demolition", "interior demo", "gut demolition", "strip out", "interior gut", "demo"],
        description: "Interior demolition of finishes, partitions, and non-structural elements. Includes debris removal and disposal.",
        specifications: {
          scope: "Remove drywall, flooring, ceilings, cabinets, fixtures, and non-structural partitions",
          protection: "Protect adjacent areas; install dust barriers",
          utilities: "Cap utilities at source; disconnect electrical and plumbing",
          disposal: "Load and haul debris; dumpster rental",
          salvage: "Separate recyclable materials if required",
        },
        materials: [
          { material: "Dumpster Rental 30yd", unit: "EA", coverage: "1 per project" },
          { material: "Dust Barrier / Zip Wall", unit: "EA", coverage: "as needed" },
          { material: "PPE", unit: "EA", coverage: "per crew" },
        ],
        unit: "SF",
        typical_price_low: 2.00,
        typical_price_high: 6.00,
      },
      {
        code: "DM-SELECTIVE",
        name: "Selective Demolition",
        aliases: ["selective demolition", "selective demo", "partial demolition", "targeted demolition"],
        description: "Targeted removal of specific elements while preserving surrounding structure. Requires careful protection.",
        specifications: {
          scope: "Remove specific walls, openings, or elements per plan",
          protection: "Protect all adjacent surfaces and structures",
          structural: "Verify load paths; shore if removing structural elements",
          utilities: "Locate and protect utilities; cap as needed",
          patching: "Patch and repair adjacent surfaces after removal",
        },
        materials: [
          { material: "Dumpster Rental", unit: "EA", coverage: "1 per project" },
          { material: "Dust Barriers", unit: "EA", coverage: "as needed" },
          { material: "Temporary Shoring if needed", unit: "EA", coverage: "varies" },
        ],
        unit: "SF",
        typical_price_low: 3.00,
        typical_price_high: 8.00,
      },
    ],
  },

  "Windows & Doors": {
    systems: [
      {
        code: "WD-VINYL-WIN",
        name: "Vinyl Window System",
        aliases: ["vinyl window", "vinyl windows", "replacement window", "vinyl replacement", "double hung vinyl", "vinyl window installation"],
        description: "Vinyl window installation with flashing, insulation, and interior/exterior trim.",
        specifications: {
          preparation: "Measure RO; verify opening size and squareness",
          installation: "Level and plumb; shims at sill and jambs",
          flashing: "Sill pan flashing; flashing tape around perimeter AAMA 2400",
          insulation: "Low-expansion foam or fiberglass insulation around perimeter",
          sealant: "Sealant at exterior perimeter; backer rod and sealant at interior",
          trim: "Interior casing and exterior brickmold or trim",
        },
        materials: [
          { material: "Vinyl Window per size", unit: "EA", coverage: "1 per opening" },
          { material: "Flashing Tape", unit: "LF", coverage: "perimeter plus sill" },
          { material: "Low-Expansion Foam", unit: "EA", coverage: "1 can per 2-3 windows" },
          { material: "Sealant", unit: "EA", coverage: "varies" },
          { material: "Interior Casing", unit: "LF", coverage: "perimeter" },
        ],
        unit: "EA",
        typical_price_low: 350.00,
        typical_price_high: 800.00,
      },
      {
        code: "WD-COMM-STOREFRONT",
        name: "Commercial Storefront System",
        aliases: ["storefront", "commercial storefront", "aluminum storefront", "curtain wall", "commercial glazing", "aluminum window wall"],
        description: "Aluminum storefront or curtain wall glazing system for commercial entrances and facades.",
        specifications: {
          framing: "Thermally broken aluminum framing; 2 x 4-1/2 inch or per system",
          glazing: "1 inch IGU insulated glass unit; tempered or laminated per code",
          installation: "Anchor to slab and header; seal all joints",
          weeps: "Weep holes in horizontal mullions for water management",
          doors: "Matching aluminum entrance doors with closer and hardware",
        },
        materials: [
          { material: "Aluminum Storefront Framing", unit: "LF", coverage: "perimeter plus mullions" },
          { material: "Insulated Glass Unit 1 inch IGU", unit: "SF", coverage: "1:1" },
          { material: "Aluminum Entrance Door", unit: "EA", coverage: "1 per opening" },
          { material: "Door Hardware closer, lock, panic", unit: "SET", coverage: "1 per door" },
          { material: "Sealant Structural and Weather", unit: "EA", coverage: "varies" },
        ],
        unit: "SF",
        typical_price_low: 35.00,
        typical_price_high: 75.00,
      },
      {
        code: "WD-HOLLOW-METAL",
        name: "Hollow Metal Door System",
        aliases: ["hollow metal door", "steel door", "commercial door", "metal door", "fire rated door", "hm door"],
        description: "Hollow metal steel door with frame, hardware, and fire rating if required. Common in commercial buildings.",
        specifications: {
          door: "16 or 18 gauge hollow metal door; fire-rated if required",
          frame: "Knock-down or welded hollow metal frame; grout fill if required",
          hardware: "Hinges, lock, closer, and panic hardware per code",
          installation: "Anchor frame to wall; plumb and square; install door",
          fire_rating: "20 min to 3 hour rated; must use listed hardware",
        },
        materials: [
          { material: "Hollow Metal Door per size", unit: "EA", coverage: "1 per opening" },
          { material: "Hollow Metal Frame", unit: "EA", coverage: "1 per opening" },
          { material: "Door Hardware Set", unit: "SET", coverage: "1 per door" },
          { material: "Grout if required", unit: "BAG", coverage: "varies" },
        ],
        unit: "EA",
        typical_price_low: 600.00,
        typical_price_high: 1500.00,
      },
    ],
  },

  "Electrical": {
    systems: [
      {
        code: "EL-ROUGH",
        name: "Electrical Rough-In",
        aliases: ["electrical rough", "rough in", "wire rough", "electrical rough in", "rough-in electrical", "wiring"],
        description: "Electrical rough-in including wiring, boxes, and conduit before walls are closed.",
        specifications: {
          wiring: "Romex NM-B or MC cable per code; conduit in commercial",
          boxes: "Device boxes at switch and outlet locations; junction boxes as needed",
          circuits: "Dedicated circuits for kitchen, laundry, HVAC; GFCI/AFCI per code",
          panel: "Load center/panelboard with breakers; grounding system",
          rough_in: "Wire pulled to boxes; stub-outs ready for devices",
        },
        materials: [
          { material: "Romex 12/2 or 14/2 250ft roll", unit: "EA", coverage: "varies by circuit" },
          { material: "Device Boxes", unit: "EA", coverage: "1 per device" },
          { material: "Breakers 15A, 20A, GFCI, AFCI", unit: "EA", coverage: "1 per circuit" },
          { material: "Panel/Load Center", unit: "EA", coverage: "1 per system" },
        ],
        unit: "EA",
        typical_price_low: 80.00,
        typical_price_high: 200.00,
      },
      {
        code: "EL-DEVICES",
        name: "Device Installation",
        aliases: ["device installation", "outlets", "switches", "receptacles", "device trim", "finish electrical"],
        description: "Installation of receptacles, switches, and lighting fixtures after drywall and paint.",
        specifications: {
          receptacles: "15A or 20A; GFCI in wet areas; tamper-resistant per code",
          switches: "Single-pole, 3-way, or 4-way per wiring; dimmer where specified",
          plates: "Nylon or metal cover plates; color per design",
          fixtures: "Install lighting fixtures; connect to rough-in wiring",
        },
        materials: [
          { material: "Receptacle 15A/20A TR", unit: "EA", coverage: "1 per location" },
          { material: "Switch SP, 3-way, dimmer", unit: "EA", coverage: "1 per location" },
          { material: "Cover Plates", unit: "EA", coverage: "1 per device" },
          { material: "Lighting Fixtures", unit: "EA", coverage: "1 per location" },
        ],
        unit: "EA",
        typical_price_low: 25.00,
        typical_price_high: 75.00,
      },
    ],
  },

  "Plumbing": {
    systems: [
      {
        code: "PL-DWV",
        name: "Drain-Waste-Vent DWV System",
        aliases: ["dwv", "drain waste vent", "drain lines", "waste lines", "vent lines", "sewer lines", "drainage"],
        description: "Drain, waste, and vent piping system for sanitary drainage. Includes pipes, fittings, and connections.",
        specifications: {
          material: "PVC DWV or ABS pipe; cast iron for high-rise or sound control",
          sizing: "1-1/2 inch min for fixtures; 3 or 4 inch main stack; per IPC/UPC",
          slope: "1/4 inch per foot for 2 inch and smaller; 1/8 inch per foot for 3 inch and larger",
          vents: "Vent through roof; wet venting per code; AAV if allowed",
          connections: "Solvent weld for PVC/ABS; no-hub couplings for cast iron",
          testing: "Water or air test per code before concealment",
        },
        materials: [
          { material: 'PVC DWV Pipe 1-1/2 to 4 inch', unit: "EA", coverage: "10-20 LF per length" },
          { material: "PVC Fittings elbows, tees, wyes", unit: "EA", coverage: "varies" },
          { material: "PVC Cement and Primer", unit: "EA", coverage: "varies" },
          { material: "Cleanouts", unit: "EA", coverage: "1 per 100 LF or per code" },
        ],
        unit: "LF",
        typical_price_low: 8.00,
        typical_price_high: 20.00,
      },
      {
        code: "PL-WATER",
        name: "Water Supply System",
        aliases: ["water supply", "water lines", "supply lines", "domestic water", "hot water lines", "cold water lines", "pex", "copper water"],
        description: "Potable water supply piping including hot and cold lines, valves, and connections to fixtures.",
        specifications: {
          material: "PEX cross-linked polyethylene or copper Type L; CPVC in some jurisdictions",
          sizing: "3/4 inch main; 1/2 inch branches; per IPC/UPC sizing calculations",
          pressure: "Test at 1.5x working pressure 100 PSI min before concealment",
          insulation: "Insulate hot water lines; insulate in unconditioned spaces",
          valves: "Shut-off valves at each fixture; main shut-off at service entry",
        },
        materials: [
          { material: 'PEX Tubing 1/2 and 3/4 inch', unit: "EA", coverage: "100 LF per coil" },
          { material: "PEX Fittings crimp or push-to-connect", unit: "EA", coverage: "varies" },
          { material: "Shut-off Valves", unit: "EA", coverage: "1 per fixture" },
          { material: "Pipe Insulation", unit: "LF", coverage: "1:1 on hot lines" },
        ],
        unit: "LF",
        typical_price_low: 6.00,
        typical_price_high: 15.00,
      },
      {
        code: "PL-FIXTURES",
        name: "Plumbing Fixture Installation",
        aliases: ["fixture installation", "toilet installation", "sink installation", "faucet", "plumbing fixtures", "fixture trim"],
        description: "Installation of plumbing fixtures including toilets, sinks, faucets, and associated hardware.",
        specifications: {
          toilets: "Set toilet on wax ring; bolt to flange; caulk base",
          sinks: "Mount sink; install faucet and drain; connect supply and waste",
          showers: "Install shower valve and trim; connect to rough-in",
          testing: "Test all fixtures for leaks; verify proper drainage",
        },
        materials: [
          { material: "Toilet per spec", unit: "EA", coverage: "1 per bathroom" },
          { material: "Sink/Lavatory", unit: "EA", coverage: "1 per location" },
          { material: "Faucet", unit: "EA", coverage: "1 per sink" },
          { material: "Shower Valve and Trim", unit: "SET", coverage: "1 per shower" },
          { material: "Wax Ring and Supply Lines", unit: "EA", coverage: "1 per toilet" },
        ],
        unit: "EA",
        typical_price_low: 150.00,
        typical_price_high: 500.00,
      },
    ],
  },
};

// Flatten all systems into a single array for searching
export const ALL_SYSTEMS = Object.entries(SCOPE_SYSTEMS).flatMap(([scope, data]) =>
  data.systems.map(sys => ({ ...sys, scope }))
);

// Get all system names for a given scope
export function systemsForScope(scope) {
  return SCOPE_SYSTEMS[scope]?.systems || [];
}

// Get a specific system by its code
export function getSystemByCode(code) {
  return ALL_SYSTEMS.find(s => s.code === code);
}

// Identify which system(s) match a given text (project description, specs, bid documents)
// Returns array of { system, scope, confidence, matchedAliases }
export function identifySystems(text) {
  if (!text || typeof text !== "string") return [];
  const lowerText = text.toLowerCase();
  const results = [];

  for (const sys of ALL_SYSTEMS) {
    const matchedAliases = (sys.aliases || []).filter(alias =>
      lowerText.includes(alias.toLowerCase())
    );
    if (matchedAliases.length > 0) {
      const confidence = Math.min(1, 0.5 + matchedAliases.length * 0.2);
      results.push({
        system: sys,
        scope: sys.scope,
        confidence,
        matchedAliases,
      });
    }
  }

  results.sort((a, b) => b.confidence - a.confidence);
  return results;
}

// Get the best-matching system for a given text and scope
export function identifySystemForScope(text, scope) {
  const matches = identifySystems(text);
  return matches.find(m => m.scope === scope) || matches[0] || null;
}

// Get a summary of all systems for display
export function getSystemSummary() {
  return Object.entries(SCOPE_SYSTEMS).map(([scope, data]) => ({
    scope,
    systemCount: data.systems.length,
    systems: data.systems.map(s => ({
      code: s.code,
      name: s.name,
      unit: s.unit,
      priceRange: "$" + s.typical_price_low.toFixed(2) + " - $" + s.typical_price_high.toFixed(2),
    })),
  }));
}