// Test matrix: every page, the entity that proves its settings saved, and key buttons to manually verify.
export const TEST_MATRIX = [
  { path: "/settings/company", title: "Company Settings", entity: "CompanyProfile", save: "Company profile saved", buttons: ["Save Profile"] },
  { path: "/settings/branding", title: "Logo / Branding", entity: "BrandAsset", save: "Brand asset saved", buttons: ["Generate Logo", "Upload", "Save"] },
  { path: "/settings/service-areas", title: "Service Areas", entity: "ScrapeSource", save: "Service area source saved", buttons: ["Add Area", "Save"] },
  { path: "/settings/trades", title: "Trade Settings", entity: "CompanyProfile", save: "Trade set on company profile", buttons: ["Save Trades"] },
  { path: "/settings/pricing", title: "Pricing Settings", entity: "PricingProfile", save: "Pricing profile saved", buttons: ["Save Pricing"] },
  { path: "/settings/proposals", title: "Proposal Template", entity: "ProposalPackage", save: "Proposal package saved", buttons: ["Save Template"] },
  { path: "/settings/notifications", title: "Notification Settings", entity: "AutomationConfig", save: "Automation config saved", buttons: ["Save"] },
  { path: "/settings/outreach", title: "Outreach Settings", entity: "EmailTemplate", save: "Email template saved", buttons: ["Save Template"] },
  { path: "/settings/ai-autonomy", title: "AI Autonomy", entity: "AutomationConfig", save: "Autonomy level saved", buttons: ["Save"] },
  { path: "/settings/team", title: "Team Roles", entity: "User", save: "Team members exist", buttons: ["Invite User"] },
  { path: "/auto-leads-setup", title: "Auto Leads Setup", entity: "ScrapeSource", save: "Lead scraper configured", buttons: ["Save Scraper"] },
  { path: "/auto-app-setup", title: "Auto App Setup", entity: "ContractorApp", save: "Contractor app created", buttons: ["Publish App"] },
  { path: "/auto-pricing-setup", title: "Auto Pricing Setup", entity: "PricingProfile", save: "Pricing profile saved", buttons: ["Save Pricing"] },
  { path: "/auto-system-setup", title: "Auto System Setup", entity: "AutomationConfig", save: "Automation config saved", buttons: ["Save Config"] },
  { path: "/auto-teams", title: "Auto Teams", entity: "User", save: "Team members exist", buttons: ["Invite"] },
  { path: "/auto-contact", title: "Auto Contact", entity: "EmailTemplate", save: "Email template / message saved", buttons: ["Save Template", "Send"] },
  { path: "/dashboard", title: "Dashboard", entity: null, save: null, buttons: ["Run Auto-Scrape"] },
  { path: "/leads", title: "Lead Discovery", entity: "Opportunity", save: "Opportunities exist", buttons: ["New Lead", "Run Discovery"] },
  { path: "/bids", title: "Bid Board", entity: "BidInvitation", save: "Bid invitations exist", buttons: ["New Bid"] },
  { path: "/projects", title: "Projects", entity: "Project", save: "Projects exist", buttons: ["New Project"] },
  { path: "/proposals", title: "Proposals", entity: "Proposal", save: "Proposals exist", buttons: ["New Proposal"] },
  { path: "/takeoff", title: "Takeoff", entity: "Takeoff", save: "Takeoffs exist", buttons: ["New Takeoff"] },
  { path: "/estimates", title: "Estimates", entity: "Estimate", save: "Estimates exist", buttons: ["New Estimate"] },
  { path: "/material-pricing", title: "Material Pricing", entity: "Material", save: "Materials exist", buttons: ["Add Material"] },
  { path: "/pricing-intelligence", title: "Pricing Intelligence", entity: "PricingProfile", save: "Pricing profile exists", buttons: ["Refresh"] },
  { path: "/messages", title: "Messages", entity: "Message", save: "Messages exist", buttons: ["New Message"] },
  { path: "/notifications", title: "Notifications", entity: "Notification", save: "Notifications exist", buttons: ["Mark Read"] },
  { path: "/tasks", title: "Task Board", entity: "ActionItem", save: "Tasks exist", buttons: ["New Task"] },
  { path: "/outreach", title: "Outreach Center", entity: "Contact", save: "Contacts exist", buttons: ["New Outreach"] },
  { path: "/scrapers", title: "Scraping", entity: "ScrapeSource", save: "Scrapers configured", buttons: ["Run Scraper"] },
  { path: "/sources", title: "Source Management", entity: "ScrapeSource", save: "Sources configured", buttons: ["Add Source"] },
  { path: "/system-health", title: "System Health", entity: "SystemScore", save: "System scores exist", buttons: ["Run Audit Now"] },
];

export const UNIQUE_ENTITIES = [...new Set(TEST_MATRIX.map((t) => t.entity).filter(Boolean))];