import React from "react";
import {CalendarClock, FileSearch, MapPinned, RefreshCw, Target, UsersRound} from "lucide-react";
import {Card, Page, PrimaryButton, SecondaryButton, SectionTitle} from "@/components/autoleads/UiPrimitives";
import {FactorRow, ProvenanceBadge, ScoreRing} from "@/components/autoleads/EnhancedPrimitives";
const factors=/** @type {any[][]} */ ([['Trade fit',0,15,'Waiting for project trade classification and organization trade profile.','blocked'],['Geographic fit',0,10,'Waiting for verified project location and service-area rules.','blocked'],['Project stage',0,10,'Waiting for source timeline and bidding-status verification.','blocked'],['Document readiness',0,10,'Plans, specifications, and addenda have not been verified.','blocked'],['Relationship strength',0,15,'No verified owner, GC, or designer relationship selected.','blocked'],['Deadline feasibility',0,10,'Bid due date has not been confirmed.','blocked'],['Margin potential',0,15,'Requires approved takeoff and organization pricing profile.','blocked'],['Source confidence',0,15,'Requires current source evidence and provenance.','blocked']]);
export default function BidabilityWorkspace(){return <Page backTo="/dashboard" eyebrow="Explainable Opportunity Scoring" title="Bidability Score" description="Decide what to pursue using independent, auditable factors rather than a mysterious AI number." actions={<><SecondaryButton><RefreshCw size={16}/>Recalculate</SecondaryButton><PrimaryButton><Target size={16}/>Run qualification</PrimaryButton></>}>
  <div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><Card className="p-6"><div className="flex flex-col items-center text-center"><ScoreRing score={0} label="Bidability"/><h2 className="mt-5 text-xl font-black">Select an opportunity</h2><p className="mt-2 max-w-sm text-sm leading-6 text-black/50">Scores are created only after project, organization, document, relationship, deadline, and pricing evidence is available.</p><div className="mt-5"><ProvenanceBadge label="Evidence required" confidence="Not scored"/></div></div><div className="mt-6 grid grid-cols-2 gap-3">{(/** @type {any[][]} */ ([[MapPinned,'Geography'],[UsersRound,'Relationships'],[FileSearch,'Documents'],[CalendarClock,'Deadline']])).map(([I,t])=><div key={t} className="rounded-xl bg-black/[.025] p-4 text-center"><I className="mx-auto text-[#a99c09]"/><div className="mt-2 text-xs font-black">{t}</div></div>)}</div></Card>
    <Card className="p-5"><SectionTitle title="Factor breakdown"/><div className="grid gap-3 md:grid-cols-2">{factors.map(x=><FactorRow key={x[0]} label={x[0]} score={x[1]} max={x[2]} reason={x[3]} state={x[4]}/>)}</div></Card></div>
  <Card className="mt-5 p-5"><SectionTitle title="Decision recommendation"/><div className="grid gap-4 md:grid-cols-3">{[['Pursue','High score, complete documents, feasible deadline, and approved margin.'],['Review','Promising opportunity with unresolved evidence or scope risk.'],['Decline','Poor fit, unavailable documents, unworkable deadline, or unacceptable risk.']].map(([t,d])=><div key={t} className="rounded-xl border border-black/10 p-4"><h3 className="font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-black/50">{d}</p></div>)}</div></Card>
</Page>}