import React,{useEffect,useState} from "react";
import {BookOpen,Building2,CalendarDays,CheckCircle2,FileCheck2,FileText,FolderOpen,MapPin,ShieldCheck,Users} from "lucide-react";
import {useNavigate,useParams} from "react-router-dom";
import {base44} from "@/api/base44Client";
import {BackLink,CommercialPage,IndustrialTitle,PrimaryAction,SecondaryAction,Surface,fmtDate,money} from "@/components/CommercialMobileUI";
export default function BidPacket(){
  const {projectId}=useParams();const nav=useNavigate();const [project,setProject]=useState(null);const [invitations,setInvitations]=useState(/** @type {any[]} */ ([]));const [takeoffs,setTakeoffs]=useState(/** @type {any[]} */ ([]));const [estimates,setEstimates]=useState(/** @type {any[]} */ ([]));const [proposals,setProposals]=useState(/** @type {any[]} */ ([]));const [loading,setLoading]=useState(true);
  useEffect(()=>{let live=true;(async()=>{const [p,inv,t,e,pr]=await Promise.all([base44.entities.Project.get(projectId).catch(()=>null),base44.entities.BidInvitation.filter({matched_project_id:projectId}).catch(()=>[]),base44.entities.Takeoff.filter({project_id:projectId}).catch(()=>[]),base44.entities.Estimate.filter({project_id:projectId}).catch(()=>[]),base44.entities.Proposal.filter({project_id:projectId}).catch(()=>[])]);if(live){setProject(p);setInvitations(inv||[]);setTakeoffs(t||[]);setEstimates(e||[]);setProposals(pr||[]);setLoading(false)}})();return()=>{live=false}},[projectId]);
  if(loading)return <CommercialPage><Surface className="p-8 text-center">Gathering verified bid packet…</Surface></CommercialPage>;
  if(!project)return <CommercialPage><BackLink to="/leads"/><IndustrialTitle compact>Bid Packet Ready</IndustrialTitle><Surface className="p-8 text-center">Project not found.</Surface></CommercialPage>;
  const tiles=[
    {icon:FolderOpen,label:"Plans / Source",count:project.source_url?"Available":"Not found",ready:!!project.source_url,onClick:()=>nav(`/projects/${project.id}/source`)},
    {icon:BookOpen,label:"Specifications",count:project.specs?"Captured":"Not found",ready:!!project.specs,onClick:()=>nav(`/projects/${project.id}`)},
    {icon:FileCheck2,label:"Bid Invitations",count:String(invitations.length),ready:invitations.length>0,onClick:()=>nav('/bid-inbox')},
    {icon:FileText,label:"Takeoffs",count:String(takeoffs.length),ready:takeoffs.length>0,onClick:()=>nav(`/projects/${project.id}/takeoff`)},
    {icon:Users,label:"Contacts",count:project.contract_info?"Captured":"Not found",ready:!!project.contract_info,onClick:()=>nav(`/projects/${project.id}`)},
    {icon:ShieldCheck,label:"Pricing / Proposal",count:proposals.length?"Proposal ready":estimates.length?"Estimate ready":"Not ready",ready:proposals.length>0||estimates.length>0,onClick:()=>proposals.length?nav('/proposals'):nav(`/projects/${project.id}/estimate`)},
  ];
  return <CommercialPage><BackLink to={`/projects/${project.id}`} label="Back to Opportunity"/><IndustrialTitle eyebrow="Bid Ready">Bid Packet Ready</IndustrialTitle>
    <Surface className="p-5"><div className="flex items-start gap-3"><span className="grid h-16 w-20 shrink-0 place-items-center rounded-xl bg-[#FFF7DA]"><Building2 size={31}/></span><div className="min-w-0 flex-1"><h2 className="text-[23px] font-bold leading-tight">{project.title}</h2><p className="mt-1 flex items-center gap-1 text-sm text-black/50"><MapPin size={14}/>{project.jurisdiction||project.address||"Location not published"}</p></div></div><div className="mt-4 grid grid-cols-3 divide-x divide-black/10 border-t border-black/[.07] pt-4"><Info label="Estimated Value" value={money(project.value,true)} accent/><Info label="Bid Due Date" value={fmtDate(project.bid_due_date)}/><Info label="Project Type" value={project.project_type||"Not classified"}/></div></Surface>
    <div className="mt-4 flex items-center gap-2 text-sm text-black/60">{project.verification_status==="verified"?<><CheckCircle2 size={20} className="text-emerald-600"/><span><strong>Verified source.</strong> Everything below is based on captured project evidence.</span></>:<><ShieldCheck size={20} className="text-amber-600"/><span><strong>Needs review.</strong> Missing packet elements stay visibly unresolved.</span></>}</div>
    <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{tiles.map(({icon:Icon,label,count,ready,onClick})=><button key={label} onClick={onClick} className="min-h-[132px] rounded-2xl border border-black/10 bg-white p-4 text-left shadow-[0_8px_20px_rgba(15,23,42,.05)]"><span className={`grid h-11 w-11 place-items-center rounded-xl ${ready?'bg-[#FFF7DA] text-[#D99D00]':'bg-black/[.03] text-black/30'}`}><Icon size={22}/></span><p className="mt-3 font-semibold">{label}</p><p className={`mt-1 text-xs ${ready?'text-black/50':'text-amber-700'}`}>{count}</p></button>)}</div>
    <Surface className="mt-4 flex items-center gap-3 p-4"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#FFF7DA]"><CalendarDays size={23}/></span><div className="flex-1"><p className="font-brand text-xs font-bold uppercase text-[#E9A900]">Next Step</p><p className="font-semibold">Review scope, specs, and missing evidence</p><p className="mt-0.5 text-sm text-black/50">Only evidence-backed quantities can advance into pricing.</p></div></Surface>
    <div className="mt-4"><PrimaryAction onClick={()=>nav(`/projects/${project.id}/takeoff`)}><FolderOpen size={20}/>Open Bid Packet</PrimaryAction><div className="mt-2 grid grid-cols-2 gap-2"><SecondaryAction onClick={()=>nav(`/projects/${project.id}`)}><Users size={17}/>Project Contact</SecondaryAction><SecondaryAction onClick={()=>nav('/tasks')}><FileCheck2 size={17}/>Team Tasks</SecondaryAction></div></div>
  </CommercialPage>;
}
function Info({label,value,accent=false}){return <div className="px-2 text-center"><p className="font-brand text-[11px] font-bold uppercase text-black/55">{label}</p><p className={`mt-2 text-sm font-black ${accent?'text-[#E9A900]':''}`}>{value||'—'}</p></div>}