import React,{useEffect,useMemo,useState} from "react";
import {CheckCircle2,Edit3,ShieldCheck,TriangleAlert} from "lucide-react";
import {useNavigate,useParams} from "react-router-dom";
import {base44} from "@/api/base44Client";
import {useAuth} from "@/lib/AuthContext";
import {BackLink,CommercialPage,DataRow,IndustrialTitle,PrimaryAction,SecondaryAction,Surface,money} from "@/components/CommercialMobileUI";
import {useOrgId} from "@/hooks/useOrgContext";

export default function EstimateWorkspace(){
  const {estimateId,projectId}=useParams();const nav=useNavigate();const {user}=useAuth();const [project,setProject]=useState(null);const [takeoffs,setTakeoffs]=useState(/** @type {any[]} */ ([]));const [estimate,setEstimate]=useState(null);const [pricing,setPricing]=useState(null);const [systems,setSystems]=useState(/** @type {any[]} */ ([]));const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
  const orgId=useOrgId();const [margin,setMargin]=useState(28);
  useEffect(()=>{let live=true;(async()=>{let est=null,pid=projectId;if(estimateId){est=await base44.entities.Estimate.get(estimateId).catch(()=>null);pid=est?.project_id||pid}const [p,t,ests,profiles,scopeSystems]=await Promise.all([pid?base44.entities.Project.get(pid).catch(()=>null):null,pid?base44.entities.Takeoff.filter({project_id:pid}).catch(()=>[]):[],pid?base44.entities.Estimate.filter({project_id:pid}).catch(()=>[]):[],base44.entities.PricingProfile.list().catch(()=>[]),base44.entities.ScopeSystem.list().catch(()=>[])]);est=est||(ests||[])[0]||null;if(live){setProject(p);setTakeoffs(t||[]);setEstimate(est);setPricing((profiles||[])[0]||null);setSystems(scopeSystems||[]);setMargin(Number(est?.margin_pct||((profiles||[])[0]?.mandatory_margin_pct)||28));setLoading(false)}})();return()=>{live=false}},[estimateId,projectId]);
  const approved=useMemo(()=>takeoffs.filter(t=>t.approval_state==="approved"),[takeoffs]);
  const breakdown=useMemo(()=>approved.map(t=>{const scopePrice=(pricing?.scope_pricing||[]).find(s=>(s.scope||'').toLowerCase()===(t.scope||'').toLowerCase());const system=systems.find(s=>s.code===t.system_code)||systems.find(s=>(s.name||'').toLowerCase()===(t.scope||'').toLowerCase());const unitPrice=Number(scopePrice?.city_mid??scopePrice?.county_mid??scopePrice?.state_mid??scopePrice?.region_mid??scopePrice?.national_mid??scopePrice?.winning_bid_price??system?.price_low??0);const qty=Number(t.final_quantity||0);return {id:t.id,label:t.scope||t.system_code||"Measured scope",qty,unit:t.unit||"",unitPrice,total:unitPrice>0&&qty>0?unitPrice*qty:null,source:scopePrice?"Pricing profile":system?"Scope system":"Missing pricing"}}),[approved,pricing,systems]);
  const missingPricing=breakdown.some(x=>!Number.isFinite(x.total)||x.total<=0);const directCost=breakdown.reduce((s,x)=>s+Number(x.total||0),0);const validMargin=Math.min(80,Math.max(0,Number(margin||0)));const sellPrice=directCost>0&&validMargin<100?directCost/(1-validMargin/100):0;const gp=sellPrice-directCost;
  const saveDraft=async()=>{if(!project||approved.length===0||missingPricing)return;setBusy(true);try{const payload={organization_id:orgId,project_id:project.id,title:`Estimate — ${project.title}`,status:"in_review",material_total:directCost,labor_total:0,equipment_total:0,overhead_total:0,subtotal:directCost,margin_pct:validMargin,margin_total:gp,grand_total:sellPrice,takeoff_ids:approved.map(t=>t.id)};const saved=estimate?.id?await base44.entities.Estimate.update(estimate.id,payload):await base44.entities.Estimate.create(payload);setEstimate(saved||{...payload,id:estimate?.id});if(project.stage==="takeoff")await base44.entities.Project.update(project.id,{stage:"estimating"})}finally{setBusy(false)}};
  const approvePrice=async()=>{if(!estimate?.id||missingPricing||approved.length===0)return;setBusy(true);try{await base44.entities.Estimate.update(estimate.id,{status:"approved",margin_pct:validMargin,margin_total:gp,grand_total:sellPrice,approved_by:user?.email||user?.id||"operator",approved_date:new Date().toISOString()});await base44.entities.PipelineEvent.create({organization_id:orgId,project_id:project.id,step:"bid",status:"completed",event_type:"estimate_price_approved",message:`Estimate ${estimate.id} approved at ${money(sellPrice)} with ${validMargin}% target margin.`,occurred_at:new Date().toISOString()});setEstimate({...estimate,status:"approved",margin_pct:validMargin,margin_total:gp,grand_total:sellPrice});if(project?.stage==="estimating")await base44.entities.Project.update(project.id,{stage:"proposal"});nav(`/projects/${project.id}/proposal`)}finally{setBusy(false)}};
  if(loading)return <CommercialPage><Surface className="p-8 text-center">Loading approved takeoffs and pricing memory…</Surface></CommercialPage>;
  if(!project)return <CommercialPage><BackLink/><IndustrialTitle compact>Estimate Summary</IndustrialTitle><Surface className="p-8 text-center">Open a project to estimate it.</Surface></CommercialPage>;
  return <CommercialPage><BackLink to={`/projects/${project.id}/takeoff`} label="Back to Takeoff"/><IndustrialTitle>Estimate Summary</IndustrialTitle>
    <Surface className="p-5"><h2 className="text-[22px] font-bold">{project.title}</h2><p className="mt-1 text-sm text-black/50">{project.jurisdiction||project.address||"Location not published"}</p><div className="mt-4 grid grid-cols-3 divide-x divide-black/10 border-t border-black/[.07] pt-4"><Metric label="Current Estimate" value={estimate?money(estimate.grand_total):sellPrice>0?money(sellPrice):"Not built"} accent/><Metric label="Target Margin" value={`${validMargin}%`}/><Metric label="Evidence" value={`${approved.length}/${takeoffs.length} approved`} success={approved.length>0&&approved.length===takeoffs.length}/></div></Surface>
    {approved.length===0?<Surface className="mt-4 p-6 text-center"><ShieldCheck size={34} className="mx-auto text-amber-600"/><p className="mt-3 font-brand text-xl font-bold uppercase">Pricing locked</p><p className="mt-2 text-sm text-black/50">No takeoff quantity has been approved. Return to the evidence-first takeoff before pricing.</p><div className="mt-4"><PrimaryAction onClick={()=>nav(`/projects/${project.id}/takeoff`)}>Review Takeoff</PrimaryAction></div></Surface>:<>
      <h3 className="mb-3 mt-6 font-brand text-[18px] font-bold uppercase">Estimate Breakdown</h3><Surface className="overflow-hidden"><div className="divide-y divide-black/[.07]">{breakdown.map(x=><div key={x.id} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="font-semibold">{x.label}</p><p className="mt-1 text-xs text-black/45">{x.qty.toLocaleString()} {x.unit} × {x.unitPrice>0?money(x.unitPrice):"pricing missing"} · {x.source}</p></div><p className={`shrink-0 font-black ${x.total?'text-black':'text-red-600'}`}>{x.total?money(x.total):"Blocked"}</p></div>)}</div></Surface>
      {missingPricing&&<Surface className="mt-3 flex items-start gap-3 border-amber-200 bg-amber-50 p-4"><TriangleAlert size={22} className="mt-0.5 shrink-0 text-amber-700"/><div><p className="font-semibold text-amber-900">Pricing memory is incomplete</p><p className="mt-1 text-sm text-amber-800">One or more approved quantities has no traceable unit-price basis. AUTOLEADS will not invent a price for it.</p></div></Surface>}
      <Surface className="mt-4 p-5"><DataRow label="Direct priced scope" value={money(directCost)}/><div className="flex min-h-14 items-center justify-between gap-4 border-b border-black/[.07]"><span className="text-sm text-black/60">Target margin</span><div className="flex items-center gap-2"><input type="number" min="0" max="80" step="0.5" value={margin} onChange={e=>setMargin(Number(e.target.value))} className="h-10 w-24 rounded-lg border border-black/15 px-3 text-right font-bold"/><span className="font-bold">%</span></div></div><DataRow label="Gross profit" value={money(gp)}/><DataRow label="Your price" value={money(sellPrice)} accent/></Surface>
      <div className="mt-4">{!estimate?<PrimaryAction onClick={saveDraft} disabled={busy||missingPricing}>{busy?"Building…":"Build Review Estimate"}</PrimaryAction>:estimate.status!=="approved"?<PrimaryAction onClick={approvePrice} disabled={busy||missingPricing}>{busy?"Saving…":"Review & Approve Price"}</PrimaryAction>:<PrimaryAction onClick={()=>nav(`/projects/${project.id}/proposal`)}><CheckCircle2 size={19}/>Price Approved — Build Proposal</PrimaryAction>}<div className="mt-2"><SecondaryAction className="w-full" onClick={()=>setMargin(Number(estimate?.margin_pct||pricing?.mandatory_margin_pct||28))}><Edit3 size={17}/>Reset Margin</SecondaryAction></div></div>
    </>}
  </CommercialPage>;
}
function Metric({label,value,accent=false,success=false}){return <div className="px-2 text-center"><p className="font-brand text-[10px] font-bold uppercase text-black/45">{label}</p><p className={`mt-2 text-sm font-black ${accent?'text-[#E9A900]':success?'text-emerald-600':''}`}>{value}</p></div>}