import React, { useState, useEffect } from "react";
import { Building2, Factory, Globe2, MapPin, Loader2, Trophy } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { Card, Page } from "@/components/autoleads/UiPrimitives";
const regions=/** @type {[React.ComponentType<any>,string,string][]} */ ([[Globe2,'National','United States'],[Factory,'State','Select State'],[MapPin,'County','Select County'],[Building2,'City','Select City']]);
const adjustments=['Labor','Material','Fuel','Equipment','Overhead','Margin','Contingency'];
export default function PricingIntelligence(){
const [benchmarks,setBenchmarks]=useState(/** @type {any[]} */ ([]));
const [loading,setLoading]=useState(true);
useEffect(()=>{(async()=>{try{const b=await base44.entities.Benchmark.list('-created_date',20);setBenchmarks(b||[]);}catch{}finally{setLoading(false);}})();},[]);
return <Page backTo="/dashboard" title="Pricing Intelligence" description="Configure pricing strategy using source-backed regional adjustments and competitor benchmarks.">
  <Card className="p-5"><h2 className="font-black">Market Comparison</h2><p className="mt-1 text-sm text-black/50">Compare costs across verified geographic levels.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{regions.map(([I,t,s])=><div key={t} className="rounded-xl border border-black/10 p-4"><div className="flex items-center gap-3"><I/><div><div className="font-black">{t}</div><div className="text-xs text-black/45">{s}</div></div></div><div className="mt-5 grid h-20 place-items-center rounded-lg bg-black/[.03] text-sm text-black/35">Set your pricing strategy</div></div>)}</div></Card>
  <Card className="mt-5 p-5"><h2 className="font-black">Pricing Strategy Controls</h2><div className="mt-4 grid gap-3 sm:grid-cols-4">{['Low','Mid','High','Custom'].map((x,i)=><button key={x} className={`rounded-xl border p-4 text-left ${i===1?'border-[#f2df0d] bg-[#fdfbe1]':'border-black/10'}`}><div className="font-black">{x}</div><div className="text-xs text-black/45">{i===0?'Competitive pricing':i===1?'Balanced approach':i===2?'Premium pricing':'Define your own'}</div></button>)}</div><h3 className="mt-6 font-black">Adjustments</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{adjustments.map(x=><div key={x} className="flex items-center gap-3 rounded-xl border border-black/10 p-4"><span className="w-24 text-sm font-bold">{x}</span><input type="range" min="-25" max="25" defaultValue="0" className="flex-1 accent-[#f2df0d]"/><span className="text-sm font-black">0%</span></div>)}</div></Card>
  {loading? <Card className="mt-5 p-5"><div className="grid place-items-center py-10"><Loader2 className="animate-spin text-[#f2df0d]" size={28}/></div></Card> :
  benchmarks.length>0 && <Card className="mt-5 p-5"><div className="flex items-center gap-2"><Trophy size={18}/><h2 className="font-black">Competitor Benchmarks</h2></div><p className="mt-1 text-sm text-black/50">{benchmarks.length} competitors indexed — see how AUTOLEADS compares.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-black/10 text-left"><th className="pb-2 font-bold">Competitor</th><th className="pb-2 font-bold">Category</th><th className="pb-2 font-bold">Pricing</th><th className="pb-2 font-bold">AI Capabilities</th><th className="pb-2 font-bold">AUTOLEADS Gap</th></tr></thead><tbody>{benchmarks.map((b,i)=><tr key={i} className="border-b border-black/5"><td className="py-2 font-bold">{b.competitor_name}</td><td className="py-2 text-black/60">{b.category?.replace(/_/g,' ')}</td><td className="py-2 text-black/60">{b.pricing_model||'—'}</td><td className="py-2 text-black/60">{b.ai_capabilities||'—'}</td><td className="py-2 text-black/60">{b.autoleads_gap||'—'}</td></tr>)}</tbody></table></div></Card>}
</Page>}