import React,{useEffect,useState} from "react";
import {Building2,CheckCircle2,ExternalLink,FileText,MapPin,ShieldCheck,Target,Users,Wrench} from "lucide-react";
import {useNavigate,useParams} from "react-router-dom";
import {base44} from "@/api/base44Client";
import {BackLink,CommercialPage,DataRow,IndustrialTitle,PrimaryAction,SecondaryAction,StatusPill,Surface,fmtDate,money} from "@/components/CommercialMobileUI";

export default function ProjectDetail(){
  const {projectId,leadId}=useParams();const id=projectId||leadId;const nav=useNavigate();const [project,setProject]=useState(null);const [takeoffs,setTakeoffs]=useState(/** @type {any[]} */ ([]));const [estimates,setEstimates]=useState(/** @type {any[]} */ ([]));const [proposals,setProposals]=useState(/** @type {any[]} */ ([]));const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
  useEffect(()=>{let live=true;(async()=>{if(!id)return;const [p,t,e,pr]=await Promise.all([base44.entities.Project.get(id).catch(()=>null),base44.entities.Takeoff.filter({project_id:id}).catch(()=>[]),base44.entities.Estimate.filter({project_id:id}).catch(()=>[]),base44.entities.Proposal.filter({project_id:id}).catch(()=>[])]);if(live){setProject(p);setTakeoffs(t||[]);setEstimates(e||[]);setProposals(pr||[]);setLoading(false)}})();return()=>{live=false}},[id]);
  const pursue=async()=>{if(!project)return;setBusy(true);try{await base44.entities.PipelineEvent.create({organization_id:project.organization_id,project_id:project.id,step:"lead",status:"completed",event_type:"pursue",message:"Operator confirmed pursuit from Opportunity Details.",occurred_at:new Date().toISOString()});if(project.stage==="qualification"){await base44.entities.Project.update(project.id,{stage:"takeoff"});setProject({...project,stage:"takeoff"})}nav(`/projects/${project.id}/takeoff`)}finally{setBusy(false)}};
  if(loading)return <CommercialPage><Surface className="p-8 text-center">Loading verified opportunity…</Surface></CommercialPage>;
  if(!project)return <CommercialPage><BackLink to="/leads" label="Back to Leads"/><IndustrialTitle compact>Opportunity Details</IndustrialTitle><Surface className="p-8 text-center">Opportunity not found.</Surface></CommercialPage>;
  const approvedTakeoffs=takeoffs.filter(t=>t.approval_state==="approved");const approvedEstimate=estimates.find(e=>e.status==="approved");const proposal=proposals[0];
  return <CommercialPage><BackLink to="/leads" label="Back to Leads"/><IndustrialTitle>Opportunity Details</IndustrialTitle>
    <Surface className="p-5"><div className="flex items-start gap-3"><span className="grid h-16 w-16 shrink-0 place-items-center rounded-full bg-[#FFF7DA]"><Building2 size={31}/></span><div className="min-w-0"><h2 className="break-words text-[24px] font-bold leading-tight">{project.title}</h2><p className="mt-1 flex items-center gap-1 text-sm text-black/50"><MapPin size={14}/>{project.jurisdiction||project.address||"Location not published"}</p></div></div>
      <div className="mt-4 grid grid-cols-3 divide-x divide-black/10 border-t border-black/[.07] pt-4"><Metric label="Estimated Value" value={money(project.value,true)} accent/><Metric label="Bid Due Date" value={fmtDate(project.bid_due_date)}/><Metric label="Source Quality" value={project.verification_status==="verified"?"Verified":"Needs Review"} success={project.verification_status==="verified"}/></div>
    </Surface>
    <div className="mt-5 flex flex-wrap gap-2">{project.verification_status==="verified"&&<StatusPill tone="success"><ShieldCheck size={11}/>Source verified</StatusPill>}{Number(project.bidability_score||0)>0&&<StatusPill tone="warning"><Target size={11}/>{Math.round(project.bidability_score)} fit score</StatusPill>}{project.trade&&<StatusPill tone="info">{project.trade}</StatusPill>}{project.project_type&&<StatusPill>{project.project_type}</StatusPill>}</div>
    <h3 className="mb-3 mt-6 font-brand text-[20px] font-bold uppercase">Why it fits you</h3><Surface className="divide-y divide-black/[.07]">
      <Fit icon={Wrench} title="Trade Match" body={project.trade?`Matched scope: ${project.trade}`:"Trade classification needs review"} ok={!!project.trade}/><Fit icon={MapPin} title="Service Area" body={project.jurisdiction||"Location not published"} ok={!!project.jurisdiction}/><Fit icon={ShieldCheck} title="Source Evidence" body={project.verification_status==="verified"?"Source has been verified":"Verification is still required"} ok={project.verification_status==="verified"}/><Fit icon={Users} title="Issuing Authority" body={project.authority||project.client_name||"Not published"} ok={!!(project.authority||project.client_name)}/>
    </Surface>
    <h3 className="mb-3 mt-6 font-brand text-[20px] font-bold uppercase">Bid Intelligence</h3><Surface className="px-5"><DataRow label="Authority" value={project.authority}/><DataRow label="Client / owner" value={project.client_name}/><DataRow label="Stage" value={project.stage}/><DataRow label="Approved takeoffs" value={String(approvedTakeoffs.length)}/><DataRow label="Approved estimate" value={approvedEstimate?money(approvedEstimate.grand_total):"Not approved"}/><DataRow label="Proposal" value={proposal?proposal.status:"Not built"}/></Surface>
    {project.description&&<Surface className="mt-4 p-5"><p className="font-brand text-sm font-bold uppercase text-[#E9A900]">Project Summary</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-black/70">{project.description}</p></Surface>}
    {project.specs&&<Surface className="mt-4 p-5"><p className="font-brand text-sm font-bold uppercase text-[#E9A900]">Verified Scope / Specs</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-black/70">{project.specs}</p></Surface>}
    {project.contract_info&&<Surface className="mt-4 p-5"><p className="font-brand text-sm font-bold uppercase text-[#E9A900]">Procurement / Contact Information</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-black/70">{project.contract_info}</p></Surface>}
    <div className="mt-5"><PrimaryAction onClick={pursue} disabled={busy}>{busy?"Working…":"🔥 Pursue This Job"}</PrimaryAction><div className="mt-2 grid grid-cols-2 gap-2"><SecondaryAction onClick={()=>nav(`/projects/${project.id}/documents`)}><FileText size={17}/>See Documents</SecondaryAction><SecondaryAction onClick={()=>nav(`/projects/${project.id}/source`)}><ExternalLink size={17}/>Open Source</SecondaryAction></div></div>
  </CommercialPage>;
}
function Metric({label,value,accent=false,success=false}){return <div className="px-2 text-center"><p className="font-brand text-[11px] font-bold uppercase text-black/55">{label}</p><p className={`mt-2 text-sm font-black ${accent?'text-[#E9A900]':success?'text-emerald-600':'text-black'}`}>{value||'—'}</p></div>}
function Fit({icon:Icon,title,body,ok}){return <div className="flex min-h-[86px] items-center gap-3 px-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#FFF7DA] text-[#D99D00]"><Icon size={22}/></span><div className="min-w-0 flex-1"><p className="font-semibold">{title}</p><p className="mt-0.5 text-sm text-black/50">{body}</p></div><CheckCircle2 size={20} className={ok?'text-emerald-600':'text-black/15'}/></div>}