import React,{useEffect,useMemo,useState} from "react";
import {BookOpen,CheckCircle2,FileText,HelpCircle,ShieldCheck,XCircle} from "lucide-react";
import {useNavigate,useParams} from "react-router-dom";
import {base44} from "@/api/base44Client";
import {BackLink,CommercialPage,IndustrialTitle,PrimaryAction,SecondaryAction,StatusPill,Surface} from "@/components/CommercialMobileUI";
import {useOrgId} from "@/hooks/useOrgContext";

const evidenceReady=t=>Boolean(t.document_id&&t.sheet&&t.scale&&t.calibrated&&t.measurement_formula&&Number.isFinite(Number(t.final_quantity))&&t.spec_evidence);
export default function TakeoffWorkspace(){
  const {projectId,takeoffId}=useParams();const nav=useNavigate();const [project,setProject]=useState(null);const [takeoffs,setTakeoffs]=useState(/** @type {any[]} */ ([]));const [loading,setLoading]=useState(true);  const [busy,setBusy]=useState(false);const [enforcing,setEnforcing]=useState(false);const [genBusy,setGenBusy]=useState(false);
  const orgId=useOrgId();
  useEffect(()=>{let live=true;(async()=>{let pid=projectId;if(!pid&&takeoffId){const t=await base44.entities.Takeoff.get(takeoffId).catch(()=>null);pid=t?.project_id}if(!pid){if(live)setLoading(false);return}const [p,t]=await Promise.all([base44.entities.Project.get(pid).catch(()=>null),base44.entities.Takeoff.filter({project_id:pid}).catch(()=>[])]);if(live){setProject(p);setTakeoffs(t||[]);setLoading(false)}})();return()=>{live=false}},[projectId,takeoffId]);
  const _approved=useMemo(()=>takeoffs.filter(t=>t.approval_state==="approved"),[takeoffs]);const ready=takeoffs.length>0&&takeoffs.every(evidenceReady);const projectRoute=project?`/projects/${project.id}`:"/leads";
  const hasMissingEvidence=takeoffs.length>0&&takeoffs.some(t=>!t.document_id||!t.sheet||!t.scale||!t.calibrated||!t.measurement_formula||!t.spec_evidence);
  const reloadTakeoffs=async()=>{const t=await base44.entities.Takeoff.filter({project_id:project.id}).catch(()=>[]);setTakeoffs(t||[])};
  const enforceEvidence=async()=>{if(!project)return;setEnforcing(true);try{await base44.functions.invoke('enforceTakeoffEvidence',{project_id:project.id});await reloadTakeoffs()}finally{setEnforcing(false)}};
  const generateTakeoff=async()=>{if(!project)return;setGenBusy(true);try{await base44.functions.invoke('autoTakeoff',{project_id:project.id});await reloadTakeoffs()}finally{setGenBusy(false)}};
  const approve=async()=>{if(!ready||!project)return;setBusy(true);try{for(const t of takeoffs){if(t.approval_state!=="approved")await base44.entities.Takeoff.update(t.id,{approval_state:"approved",reviewer_decision:"approved"})}await base44.entities.PipelineEvent.create({organization_id:orgId,project_id:project.id,step:"takeoff",status:"completed",event_type:"evidence_takeoff_approved",message:`${takeoffs.length} evidence-backed takeoff item(s) approved.`,occurred_at:new Date().toISOString()});if(project.stage==="takeoff")await base44.entities.Project.update(project.id,{stage:"estimating"});setTakeoffs(takeoffs.map(t=>({...t,approval_state:"approved",reviewer_decision:"approved"})));nav(`/projects/${project.id}/estimate`)}finally{setBusy(false)}};
  if(loading)return <CommercialPage><Surface className="p-8 text-center">Loading evidence…</Surface></CommercialPage>;
  if(!project)return <CommercialPage><BackLink to="/leads"/><IndustrialTitle compact>Evidence First Takeoff</IndustrialTitle><Surface className="p-8 text-center">Open a project before reviewing takeoff evidence.</Surface></CommercialPage>;
  return <CommercialPage><BackLink to={projectRoute} label="Back to Opportunity"/><IndustrialTitle>Evidence First Takeoff</IndustrialTitle>
    <Surface className="p-5"><p className="font-brand text-xs font-bold uppercase text-[#E9A900]">Project</p><h2 className="mt-1 text-xl font-bold">{project.title}</h2><p className="mt-1 text-sm text-black/50">Every quantity below must trace back to a document, sheet, scale, formula, and specification.</p></Surface>
    {takeoffs.length===0?<Surface className="mt-4 p-7 text-center"><ShieldCheck size={34} className="mx-auto text-[#D99D00]"/><p className="mt-3 font-brand text-xl font-bold uppercase">No evidence-backed takeoff yet</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-black/50">Generate an evidence-backed takeoff from the project specs. AUTOLEADS extracts document references, plan sheets, scales, and measurement formulas automatically.</p><div className="mt-4 grid grid-cols-2 gap-2"><SecondaryAction onClick={()=>nav(`/projects/${project.id}/bid-packet`)}><FileText size={19}/>Bid Packet</SecondaryAction><PrimaryAction onClick={generateTakeoff} disabled={genBusy}>{genBusy?"Generating…":"Generate Takeoff"}</PrimaryAction></div></Surface>:<>
      <div className="mt-4 space-y-4">{takeoffs.map(t=><Surface key={t.id} className="overflow-hidden"><div className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-brand text-xs font-bold uppercase text-[#E9A900]">{t.system_code||"Measured scope"}</p><h3 className="mt-1 text-lg font-bold">{t.scope||"Unlabeled scope"}</h3></div><StatusPill tone={t.approval_state==="approved"?"success":evidenceReady(t)?"warning":"danger"}>{t.approval_state==="approved"?"Approved":evidenceReady(t)?"Ready for review":"Needs evidence"}</StatusPill></div>
        <div className="mt-4 rounded-xl border border-black/[.07] bg-black/[.015] p-4"><div className="grid grid-cols-3 gap-2 text-center"><Quantity label="Final Quantity" value={Number.isFinite(Number(t.final_quantity))?Number(t.final_quantity).toLocaleString():"—"} unit={t.unit}/><Quantity label="Sheet" value={t.sheet||"—"}/><Quantity label="Confidence" value={t.confidence!=null?`${Math.round(Number(t.confidence)*100)}%`:"—"}/></div></div>
        <div className="mt-3 grid gap-2 sm:grid-cols-2"><Evidence ok={!!t.document_id} label="Document linked" detail={t.document_id||"Missing"}/><Evidence ok={!!t.sheet} label="Plan sheet" detail={t.sheet||"Missing"}/><Evidence ok={!!t.scale&&!!t.calibrated} label="Scale confirmed" detail={t.scale||"Missing"}/><Evidence ok={!!t.measurement_formula} label="Measurement formula" detail={t.measurement_formula||"Missing"}/><Evidence ok={!!t.spec_evidence} label="Specs matched" detail={t.spec_evidence||"Missing"}/><Evidence ok={Number.isFinite(Number(t.final_quantity))} label="Quantity calculated" detail={t.final_quantity!=null?`${Number(t.final_quantity).toLocaleString()} ${t.unit||''}`:"Missing"}/></div>
      </div></Surface>)}</div>
      <Surface className="mt-4 p-4"><p className="font-brand text-sm font-bold uppercase">Evidence Trust Checklist</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Trust ok={takeoffs.every(t=>!!t.document_id)} label="Plans found"/><Trust ok={takeoffs.every(t=>!!t.scale&&!!t.calibrated)} label="Scale confirmed"/><Trust ok={takeoffs.every(t=>!!t.spec_evidence)} label="Specs matched"/><Trust ok={ready} label="All quantities traceable"/></div>{hasMissingEvidence&&<div className="mt-3"><PrimaryAction onClick={enforceEvidence} disabled={enforcing}>{enforcing?"Generating evidence…":"Generate Missing Evidence"}</PrimaryAction><p className="mt-2 text-center text-xs text-black/50">AUTOLEADS will extract document references, plan sheets, scales, and formulas from the project specs.</p></div>}</Surface>
      <div className="mt-4"><PrimaryAction onClick={approve} disabled={!ready||busy}>{busy?"Approving…":"Approve Takeoff"}</PrimaryAction>{!ready&&<p className="mt-2 text-center text-xs font-semibold text-red-600">Approval is locked until every quantity has the required evidence.</p>}<div className="mt-2 grid grid-cols-2 gap-2"><SecondaryAction onClick={()=>nav(`/projects/${project.id}/bid-packet`)}><BookOpen size={17}/>View Packet</SecondaryAction><SecondaryAction onClick={()=>nav(`/projects/${project.id}`)}><HelpCircle size={17}/>Review Source</SecondaryAction></div></div>
    </>}
  </CommercialPage>;
}
function Quantity({label,value,unit=""}){return <div><p className="font-brand text-[10px] font-bold uppercase text-black/45">{label}</p><p className="mt-1 text-xl font-black text-[#E9A900]">{value}</p>{unit&&<p className="text-xs text-black/50">{unit}</p>}</div>}
function Evidence({ok,label,detail}){return <div className="flex items-start gap-2 rounded-lg border border-black/[.07] p-3">{ok?<CheckCircle2 size={18} className="mt-0.5 shrink-0 text-emerald-600"/>:<XCircle size={18} className="mt-0.5 shrink-0 text-red-500"/>}<div className="min-w-0"><p className="text-sm font-semibold">{label}</p><p className="mt-0.5 line-clamp-2 text-xs text-black/45">{detail}</p></div></div>}
function Trust({ok,label}){return <div className="text-center">{ok?<CheckCircle2 size={24} className="mx-auto text-emerald-600"/>:<XCircle size={24} className="mx-auto text-red-500"/>}<p className="mt-1 text-xs font-semibold">{label}</p></div>}