import React from "react";
import {ArrowLeft,Bell,ChevronRight,MessageSquare} from "lucide-react";
import {useNavigate} from "react-router-dom";
export const money=(value,compact=false)=>{const n=Number(value);if(!Number.isFinite(n))return "—";if(compact){const abs=Math.abs(n);if(abs>=1000000000)return `$${(n/1000000000).toFixed(abs>=10000000000?1:2).replace(/\.0+$/,'')}B`;if(abs>=1000000)return `$${(n/1000000).toFixed(abs>=10000000?1:2).replace(/\.0+$/,'')}M`;if(abs>=1000)return `$${(n/1000).toFixed(abs>=100000?0:1).replace(/\.0$/,'')}K`}return `$${Math.round(n).toLocaleString()}`};
export const fmtDate=(value)=>{if(!value)return "Not published";const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})};
export const CommercialPage=({children,className=""})=><div className={`min-h-screen overflow-x-hidden bg-white pb-28 text-[#050708] ${className}`}><div className="mx-auto w-full max-w-[980px] px-5 pt-5 sm:px-7 lg:px-10 lg:pt-8">{children}</div></div>;
export function BrandHeader({messageCount=0,notificationCount=0}){return <div className="mb-7 flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-[10px] border-[3px] border-[#FFC400] font-brand text-xl font-bold text-[#FFC400]">A</span><div className="font-brand text-[24px] font-bold italic tracking-[-.03em]">AUTO<span className="text-[#E9A900]">LEADS</span></div></div><div className="flex gap-2"><HeaderIcon icon={MessageSquare} count={messageCount}/><HeaderIcon icon={Bell} count={notificationCount}/></div></div>}
function HeaderIcon({icon:Icon,count}){return <span className="relative grid h-11 w-11 place-items-center rounded-full border border-black/10"><Icon size={19}/>{count>0&&<span className="absolute -right-1 -top-1 grid min-h-5 min-w-5 place-items-center rounded-full bg-[#FFC400] px-1 text-[10px] font-black">{count>9?'9+':count}</span>}</span>}
export function BackLink({to="/dashboard",label="Back"}){const nav=useNavigate();return <button onClick={()=>nav(to)} className="mb-4 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-black/70"><ArrowLeft size={20}/>{label}</button>}
export const Greeting=({name="Builder",line="Let's win today."})=><div className="mb-2"><p className="text-[22px] font-medium tracking-[-.02em]">Good morning, <span className="text-[#E9A900]">{name}</span></p><p className="mt-1 text-sm text-black/45">☀ {line}</p></div>;
export function IndustrialTitle({children,eyebrow="",compact=false}){return <div className="mb-6">{eyebrow&&<p className="mb-1 font-brand text-[14px] font-bold uppercase tracking-[.08em] text-[#E9A900]">{eyebrow}</p>}<h1 className={`font-brand font-bold uppercase leading-[.94] tracking-[-.025em] ${compact?'text-[38px] sm:text-[44px]':'text-[48px] sm:text-[56px] lg:text-[64px]'}`}>{children}</h1><div className="mt-3 h-[4px] w-[58%] max-w-[390px] rounded-full bg-[#FFC400]"/></div>}
export function SectionHeader({title,actionLabel="",onAction}){return <div className="mb-3 mt-6 flex items-center justify-between gap-3"><h2 className="font-brand text-[17px] font-bold uppercase tracking-[.035em]">{title}</h2>{actionLabel&&<button onClick={onAction} className="inline-flex min-h-10 items-center gap-1 text-sm font-semibold text-[#D99D00]">{actionLabel}<ChevronRight size={17}/></button>}</div>}
export function Surface({children=null,className="",onClick=undefined}){return <section onClick={onClick} className={`rounded-[16px] border border-black/10 bg-white shadow-[0_8px_24px_rgba(15,23,42,.06)] ${onClick?'cursor-pointer':''} ${className}`}>{children}</section>}
export function StatusPill({children,tone="neutral"}){const styles={success:"border-emerald-200 bg-emerald-50 text-emerald-700",warning:"border-amber-200 bg-amber-50 text-amber-700",danger:"border-red-200 bg-red-50 text-red-700",info:"border-blue-200 bg-blue-50 text-blue-700",purple:"border-violet-200 bg-violet-50 text-violet-700",neutral:"border-black/10 bg-black/[.03] text-black/55"};return <span className={`inline-flex items-center gap-1 rounded-md border px-2 py-1 text-[10px] font-bold ${styles[tone]||styles.neutral}`}>{children}</span>}
export const PrimaryAction=({children,onClick,disabled=false,className=""})=><button onClick={onClick} disabled={disabled} className={`flex min-h-[56px] w-full items-center justify-center gap-2 rounded-[10px] bg-[#FFC400] px-5 font-brand text-[18px] font-bold uppercase tracking-[.035em] shadow-[0_8px_20px_rgba(255,196,0,.22)] disabled:opacity-40 ${className}`}>{children}</button>;
export const SecondaryAction=({children,onClick,disabled=false,className=""})=><button onClick={onClick} disabled={disabled} className={`flex min-h-[52px] items-center justify-center gap-2 rounded-[10px] border border-black/20 bg-white px-4 font-brand text-[15px] font-bold uppercase tracking-[.025em] disabled:opacity-40 ${className}`}>{children}</button>;
export function IconSquare({icon:Icon,tone="yellow"}){const cls=tone==='danger'?'bg-red-50 text-red-600':tone==='success'?'bg-emerald-50 text-emerald-600':'bg-[#FFC400] text-black';return <span className={`grid h-12 w-12 shrink-0 place-items-center rounded-[11px] ${cls}`}><Icon size={23}/></span>}
export function DataRow({label="",value="",accent=false,children=null}){return <div className="flex min-h-12 items-center justify-between gap-3 border-b border-black/[.07] py-2.5 last:border-b-0"><span className="text-sm text-black/60">{label}</span><span className={`text-right text-sm font-bold ${accent?'text-[#E9A900]':'text-black'}`}>{children||value||'—'}</span></div>}